### DISCUSSION TITLE
Total Solar Field: Failure in the HA Log with float value

### DISCUSSION THREAD

**Discussion by masterjedi** [wlcrs/huawei_solar#1016] [Setting up the integration]
I have update my code, because i have a Failure in my HA log:

Template error: float got invalid input ‘unknown’ when rendering template

```
template:
  - sensor:
      - name: "energy_pv"
        unique_id: "PV Energy"
        state: >
          {{ (states('sensor.inverter_total_yield') | float) - (states('sensor.batteries_total_discharge') | float) + (states('sensor.batteries_total_charge') | float) }}
        device_class: energy
        state_class: total_increasing
        unit_of_measurement: 'kWh'

      - name: "energy_pv_daily"
        unique_id: "PV Energy daily"
        state: >
          {% if is_state("sun.sun", "above_horizon") %} {{ (states('sensor.inverter_daily_yield') | float) - (states('sensor.batteries_day_discharge') | float) + (states('sensor.batteries_day_charge') | float) }}
          {% else %} 0
          {% endif %}
        device_class: energy
        state_class: total_increasing
        unit_of_measurement: 'kWh'
```

I have put a 0 after float.

Now I have the complete annual yield between 10 and 11 o'clock in the energy dashboard.

So sieht es aus:

       {{ (states('sensor.inverter_total_yield') | float(0)) - (states('sensor.batteries_total_discharge') | float(0)) + (states('sensor.batteries_total_charge') | float(0)) }}

![image](https://github.com/user-attachments/assets/40860e47-dde4-43b2-b3e8-643ae4534862)

Whar is the Problem?
