### DISCUSSION TITLE
Error handling

### DISCUSSION THREAD

**Discussion by Rhysgh** [wlcrs/huawei_solar#252] [Ideas]
Hey, I wanted to set a mobile notification when the integration fails,  right now, I'm checking for one of the sensors on. That integration going to an unknown state, but I don’t like this method

In the log, there is this
Logger: huawei_solar.huawei_solar
Source: /usr/local/lib/python3.10/site-packages/huawei_solar/huawei_solar.py:277 
First occurred: 06:50:06 (2 occurrences) 
Last logged: 06:52:25
Modbus client is not connected to the inverter.
NoneType: None

Surly I can use a listener or something to trigger based on logs instead of sensor states.

Any tips?

**Comment by tarmor1** [comment]
I myself have the following Automation set if inverter throws an Error, unless inverter is unavailable.
Luckily former hasn't occurred and latter is rare.
Hope it helps!
```
alias: Notify and Count Inverter Alarms
description: Notify and Count Inverter Alarms
trigger:
  - platform: state
    entity_id:
      - sensor.inverter_alarms
    from: None
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.inverter_alarms
        state: unavailable
action:
  - service: counter.increment
    data: {}
    target:
      entity_id: counter.count_inverter_warnings
  - device_id: ...my mobile device id....
    domain: mobile_app
    type: notify
    message: Inverter Warning
mode: single

```
