### DISCUSSION TITLE
Daily Solar Yield

### DISCUSSION THREAD

**Discussion by woopstar** [wlcrs/huawei_solar#303] [Ideas]
Would'nt the daily solar yield actually just be as simple as:

Daily Solar Yield = Inverter Daily yield - Battery Day discharge

Something like:
```
- sensor:
  - name: "Daily Solar Yield"
    unique_id: "daily_solar_yield"
    unit_of_measurement: kWh
    icon: mdi:solar-power
    device_class: energy
    state_class: total_increasing
    attributes:
      last_reset: "1970-01-01T00:00:00+00:00"
    state: >-
      {{ (states('sensor.inverter_daily_yield') | float - states('sensor.battery_day_discharge') | float) | round(3, default=0) }}
```
