### DISCUSSION TITLE
MQTT

### DISCUSSION THREAD

**Discussion by ralf2201** [wlcrs/huawei_solar#336] [General]
I would like to send the results to a mqtt broker and then also to a influxdb for further usage of the data. The mqtt broker does not run on home assistant.
How would i manage that.

**Comment by tarmor1** [comment]
If you have MQTT broker running, you can make HA automation that publishes the value(s) to MQTT once they change?

```

  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: mytopic
      payload: mypayload
```
