### DISCUSSION TITLE
Turning off output to the grid?

### DISCUSSION THREAD

**Discussion by Dennisreneholm** [wlcrs/huawei_solar#382] [General]
Hi.

Big thanks for creating this integration, i love having my solar in HA!

I live in Denmark, where the sales price of electricity can sometime be negative, so it's costing me money to send power to the grid.
I've written with Huawei support, and they say it's possible to turn off the power to the grid via the modbus. See attached pdf.

Can this be done using this integration?
Its called "Zero Export Limitation"

I want an automation that turns this on, when the sales price is negative, and back on when it's positive :)

Best regards!
[2023INVL1008 Zero export limitation on SUN2000 (2-6)KTL-L1 inverters.pdf](https://github.com/wlcrs/huawei_solar/files/11564754/2023INVL1008.Zero.export.limitation.on.SUN2000.2-6.KTL-L1.inverters.pdf)

**Comment by ghost** [comment]
I did a bit of digging into this myself this evening. I was looking to see if I could add this control to the integration by doing something similar to [defining a custom sensor](https://github.com/wlcrs/huawei_solar/wiki/Defining-custom-sensors). In scrolling through the different files I discovered that this is already part of the integration!

I saw this in services.yaml
![services_yaml](https://github.com/wlcrs/huawei_solar/assets/111027210/d9fdfa64-b3a9-4097-a222-b44fd9e07dfa)

And sure enough there they are in HA>Devtools>Services:
![service_list](https://github.com/wlcrs/huawei_solar/assets/111027210/a304f4cc-ee34-42fb-a854-45beb5d5780f)
(which I had no idea were even there! Turns out though, [it's already in the wiki](https://github.com/wlcrs/huawei_solar/wiki/Changing-Active-Power-Control))

So I tested a couple of the services - it takes a minute to update and show within the FusionSolar portal, but it works:

![limit_0](https://github.com/wlcrs/huawei_solar/assets/111027210/8db6ebe2-64b9-4458-bd06-07aa6b248ff2)
![limit_3680](https://github.com/wlcrs/huawei_solar/assets/111027210/0525170e-410d-466d-a686-e00ab303f2fe)
![unlimited](https://github.com/wlcrs/huawei_solar/assets/111027210/92770d8e-4698-4f5d-bc9b-800fa7744d66)

Anyway, whilst it's not actually changing _Active Power Control Mode_ to 'Zero Export Limitation', using the above service to set _Max. grid feed-in power_ to zero is functionally the same thing. So you (and I!) can just call that service with whatever parameters in an automation. 

Top work as ever from wlcrs! 👏

**Comment by Dennisreneholm** [comment]
This looks perfect!
I don't have those services though? i'm guessing i need to elevate the permissions.
How do i do that, when i already have it configured without the elevated permissions?

EDIT:
I removed the integration and added it again, and now i can have the elevated permission added.
And i now have the same options as you've shown. and it works fine. I can see it draws a bit of power from the grid when we set the output to zero, but that's a cheaper option than paying for the massive amount of power sent to the grid when the price is negative.

**Reply by ghost** [reply]
That's exactly how I did it, remove and re-add, it's seamless.

And yeah, I've noticed similar regarding grid consumption when zero export is set. I think this is because the inverter, with a zero export limit, will never make _quite_ enough to cover your consumption, so that it will never have 'too much' and need to dump to grid.

In my case, it's not a cost to export, but the fact that in the early afternoon on a sunny day, grid voltage is going too high, causing my inverter to throttle right down to ~160w until grid voltage returns back to acceptable parameters. Either the network operator is messing up, or, more likely given the times and weather conditions when this has happened, someone nearby is exporting when they shouldn't be... Anyway, when this happens, it leads me to importing electricity through the day. With zero export limit set when voltage is too high, the inverter covers ~95% of my consumption, so I'm importing _much_ less - but I don't want to leave it at that for the next couple of months, and pay for 5% of my energy for the majority of the time that I don't need to. Hence wanting to automate it!

Going a bit off the rails from your case here, but for the benefit of anyone who is experiencing the same thing as me, here's the automation I wrote last night after studying different integration sensor data from periods when the throttling I've experienced happens. Note though, it's not needed to fire yet so I've no idea if it'll work or if I need to tweak it more 😅 You could probably use it by swapping out the trigger and conditions etc for your price sensor, though.

```
alias: Inverter - On High Grid Voltage etc, Set Export to 0
trigger:
  - platform: numeric_state
    entity_id: sensor.inverter_reactive_power
    for:
      hours: 0
      minutes: 1
      seconds: 0
    above: 50
condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.power_meter_active_power
        below: -100
      - condition: numeric_state
        entity_id: sensor.inverter_input_power
        below: 200
      - condition: numeric_state
        entity_id: sensor.inverter_active_power
        below: 200
      - condition: numeric_state
        entity_id: sensor.power_meter_voltage
        above: 248
      - condition: time
        after: "11:00:00"
        before: "18:00:00"
action:
  - service: huawei_solar.set_maximum_feed_grid_power
    data:
      power: "0"
      device_id: #redacted
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: notify.notification_group
    data:
      title: "⚡Export: Disabled"
      message: >-
        "Grid voltage too high. Export re-enables when conditions improve, or in 2hrs automatically."
  - wait_for_trigger:
      - platform: numeric_state
        entity_id: sensor.power_meter_voltage
        for:
          hours: 0
          minutes: 5
          seconds: 0
        below: 248
    timeout:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: huawei_solar.set_maximum_feed_grid_power
    data:
      power: "3680"
      device_id: #redacted
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: notify.notification_group
    data:
      title: "⚡Export: Re-enabled"
      message: >-
        "Grid voltage acceptable, or, automatic restoration after 2 hour timeout."
mode: single
```

**Reply by sjaanus** [reply]
@Dennisreneholm 
How much electricity does your system draw from the grid? Are the power consumption levels of each phase relatively similar? 

In Estonia, even when the electricity prices are set at 0, it is not good to sell back to the grid due to the additional cost of approximately 0.5 cents per kilowatt-hour (kWh) as a margin. On the other hand, if you were to buy electricity at 0 cost, you would still need to pay grid fees amounting to approximately 5-7 cents/kWh. Consequently, purchasing electricity from the grid becomes around 10 times more expensive due to these grid fees. Therefore, it is advisable to avoid buying electricity from the grid altogether.

**Reply by Dennisreneholm** [reply]
It sounds like pretty much the same system as in Denmark.
I limit the output to the grid to 200 watt. it then reduces the solar being produced. So my home is still running on 100% solar, and the 200 watt i use as a "buffer" since the power draw fluctuates a bit, so if i set it to zero, i will be drawing some from the grid, which i don't want.

Did that answer your question?

**Reply by dim123dim123** [reply]
any idea why when I set set_maximum_feed_grid_power_percent the Active power is 1-4W?

**Reply by Roving-Ronin** [reply]
@Kimfamous instead of using:

```
  - service: huawei_solar.set_maximum_feed_grid_power
    data:
      power: "3680"
      device_id: #redacted
```
Have you looked at using the following, that is the service that resets the inverter (of whatever size you have, so no need for declaring xxx watts) back to full export capacity ?

```
  - service: huawei_solar.reset_maximum_feed_grid_power
    data:
      device_id: #redacted
```
