### DISCUSSION TITLE
Displaying Custom Value

### DISCUSSION THREAD

**Discussion by ObviousInvestor** [wlcrs/huawei_solar#390] [General]
Hi Folks, I'm very new to HA (like first install 2 day ago new) so please bear with me.

I have the huawei_solar integration up and running (brilliant BTW, thanks to the developers for the work). The only thing I need to do now is, in order to display my house "current load" I need to find a way to subtract "Power Meter Active Power" from the "Inverter Active Power" and display the answer (and get access to it through automation).  I'm not sure if my solar was installed incorrectly or something, but there seems to be no sensor that just displays the load from the house. The Power Meter Sensor  shows input and export from the grid, and the Inverter Active Power shows the load, plus battery charge plus export to the grid.

Would one of you good people be able to point me in the direction of how I might do that please? I'm not a developer so I'll need pretty detailed instructions, or a link to where I can find them

Thanks in advance for any help.

**Comment by ObviousInvestor** [comment]
Got it for anyone interested;

In config.yaml file

group:
  meter_readings:
    name: Meter readings
    entities:
      - sensor.inverter_active_power
      - sensor.power_meter_active_power
      

sensor:
  - platform: template
    sensors:
        total_load:
            friendly_name: "Load (total)"
            unit_of_measurement: 'W'
            value_template: '{{ states("sensor.inverter_active_power") |int - states("sensor.power_meter_active_power") | int }}'

**Reply by Roving-Ronin** [reply]
Suggest looking at creating a packages folder, so you can add individual yaml files for the various sensors / templates / energy costs you want going forward. Dumping everything in configuration.yaml will see it grow and be hard to track the flows in it.  https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder

BTW the format of template sensors has been updated in HA, below is the new / going forward format for what you want:
```
template:
  - sensor:
      # Shows the calculated current load, in Watts
    - name: "Power Meter - Active Load"
      unique_id: power_meter_active_load
      unit_of_measurement: "W"
      device_class: "power"
      state_class: measurement
      state: "{{ states("sensor.inverter_active_power") | float(0) - states("sensor.power_meter_active_power") | float(0) | round(3) }}"
```

I'm waiting for an additional modbus server, to try access my power meter, so I can't test and confirm your formula above. But the yaml above should be correct, just update sensors being called if required.
