### DISCUSSION TITLE
About solar production in Energy panel

### DISCUSSION THREAD

**Discussion by wavelov3r** [wlcrs/huawei_solar#430] [Setting up the integration] [answered]
According to the [ image ](https://raw.githubusercontent.com/wlcrs/huawei_solar/main/images/energy-config.png), in Solar production should be inserted "Inverter Daily Yeld" sensor... but isn't wrong?

My energy dashboard is confused, i think due to this setting... (all the values has been checked, and are ok).
Here a screen:
![image](https://github.com/wlcrs/huawei_solar/assets/104383649/b59b9a15-dadf-4d3a-8dbd-2e645d568ee8)

I've tried to [change the sensor config](https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics) because in the dropdown are shown only 2 inverters sensor, but without success :(

```
homeassistant:
  customize_glob:
    sensor.inverter_input_power:
      last_reset: '1970-01-01T00:00:00+00:00'
      state_class: total_increasing
      unit_of_measurement: kWh
      device_class: energy
```

tried with state_class measurement also. 

Where am i wrong?
