### DISCUSSION TITLE
Daily Solar Yield yaml error

### DISCUSSION THREAD

**Discussion by graphistudio** [wlcrs/huawei_solar#459] [Setting up the integration] [answered]
I want to use this solution:

https://github.com/wlcrs/huawei_solar/wiki/Daily-Solar-Yield

But when I add this code to the configuration.yaml:

```


sensor:
  - platform: integration
    source: sensor.input_power_with_efficiency_loss
    name: solar_energy_riemann
    round: 3

template:
  - sensor:
    - name: "input_power_with_efficiency_loss"
      unique_id: "input_power_with_efficiency_loss"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      state: >-
        {% set inverter_rating = 3000 %} {# adjust this value to the rated power of your inverter #}
        {% set inpower = states('sensor.inverter_input_power')|float(0) %}
        {% if inpower < (inverter_rating*0.1) %}
          {{ inpower * 0.90 }}
        {% elif inpower < (inverter_rating*0.2) %}  
          {{ inpower * 0.95 }}
        {% else %}
          {{ inpower * 0.98 }}
        {% endif %}

template:
  - sensor:
      - name: energy_pv
        friendly_name: "PV Energy"
        unique_id: "PV Energy"
        value_template: "{{ (states('sensor.inverter_total_yield') | float) - (states('sensor.battery_total_discharge') | float) + (states('sensor.battery_total_charge') | float)}}"
        device_class: energy      
        state_class: total
        unit_of_measurement: kWh
      - name: energy_pv_daily
        friendly_name: "PV Energy daily"
        unique_id: "PV Energy daily"
        value_template: "{{ (states('sensor.inverter_daily_yield') | float) - (states('sensor.battery_day_discharge') | float) + (states('sensor.battery_day_charge') | float)}}"
        device_class: energy
        state_class: total
        unit_of_measurement: kWh

```

I receive the following errors:

Invalid config for [template]: [value_template] is an invalid option for [template]. Check: template->sensor->0->value_template. (See /config/configuration.yaml, line 37).
Invalid config for [template]: required key not provided @ data['sensor'][0]['state']. Got None. (See /config/configuration.yaml, line 37).
Invalid config for [template]: required key not provided @ data['sensor'][1]['state']. Got None. (See /config/configuration.yaml, line 37).
Invalid config for [template]: [friendly_name] is an invalid option for [template]. Check: template->sensor->0->friendly_name. (See /config/configuration.yaml, line 36).
Invalid config for [template]: [friendly_name] is an invalid option for [template]. Check: template->sensor->0->friendly_name. (See /config/configuration.yaml, line 49).

Any idea?

Please can you share a working configuration.yaml file?

Thanks

**Comment by Roving-Ronin** [comment]
@graphistudio 
To paste yaml code into a post, please add 3x backtick (the key to the left of the top row #1 on your keyboard) before and after the code. This will allow the code to retain its formatting.

Also, just to make sure, are you saying that is the exact contents of your configuration.yaml file?  If so, I'd suggest

a) reading this about making a packages folder https://www.home-assistant.io/docs/configuration/packages/ 

Short version add this to your configuration.yaml, and then in the /config directory of your HA instance create a folder named 'packages'.
`
homeassistant:
  packages: !include_dir_merge_named packages/
`
Into this /packages directory you can then add yaml files for whatever you need. i.e. huawei_solar.yaml and stick all the extra code you need for this integation and your own needs, into that yaml file.

b) Looking at the HA documentation and other examples on here, that create sensors etc in yaml files. In there you'll note that you can't have template: defined twice in the same yaml file. If you've made that error, I think your looking to use (and modify to your inverters sensor names, if you have multiple inverters/inputs):

```
sensor:
  - platform: integration
    source: sensor.input_power_with_efficiency_loss
    name: solar_energy_riemann
    round: 3

template:
  - sensor:
    - name: "input_power_with_efficiency_loss"
      unique_id: "input_power_with_efficiency_loss"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      state: >-
        {% set inverter_rating = 5000 %} {# adjust this value to the rated power of your inverter #}
        {% set inpower = states('sensor.inverter_input_power')|float(0) %}
        {% if inpower < (inverter_rating*0.1) %}
          {{ inpower * 0.90 }}
        {% elif inpower < (inverter_rating*0.2) %}  
          {{ inpower * 0.95 }}
        {% else %}
          {{ inpower * 0.98 }}
        {% endif %}

  - sensor:
      - name: energy_pv
        friendly_name: "PV Energy"
        unique_id: "PV Energy"
        value_template: "{{ (states('sensor.inverter_total_yield') | float) - (states('sensor.battery_total_discharge') | float) + (states('sensor.battery_total_charge') | float)}}"
        device_class: energy      
        state_class: total
        unit_of_measurement: kWh
      - name: energy_pv_daily
        friendly_name: "PV Energy daily"
        unique_id: "PV Energy daily"
        value_template: "{{ (states('sensor.inverter_daily_yield') | float) - (states('sensor.battery_day_discharge') | float) + (states('sensor.battery_day_charge') | float)}}"
        device_class: energy
        state_class: total
        unit_of_measurement: kWh
```

**Reply by graphistudio** [reply, marked as answer]
I solved by using this code:  


```
sensor:
  - platform: integration
    source: sensor.input_power_with_efficiency_loss
    name: solar_energy_riemann
    round: 3

template:
  - sensor:
    - name: "input_power_with_efficiency_loss"
      unique_id: "input_power_with_efficiency_loss"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      state: >-
        {% set inverter_rating = 6000 %} {# adjust this value to the rated power of your inverter #}
        {% set inpower = states('sensor.inverter_input_power')|float(0) %}
        {% if inpower < (inverter_rating*0.1) %}
          {{ inpower * 0.90 }}
        {% elif inpower < (inverter_rating*0.2) %}  
          {{ inpower * 0.95 }}
        {% else %}
          {{ inpower * 0.98 }}
        {% endif %}


  - sensor:
      - name: energy_pv
        #friendly_name: "PV Energy"
        unique_id: "PV Energy"
        state: "{{ (states('sensor.inverter_total_yield') | float) - (states('sensor.battery_total_discharge') | float) + (states('sensor.battery_total_charge') | float)}}"
        device_class: energy      
        state_class: total
        unit_of_measurement: kWh
      - name: energy_pv_daily
        #friendly_name: "PV Energy daily"
        unique_id: "PV Energy daily"
        state: "{{ (states('sensor.inverter_daily_yield') | float) - (states('sensor.battery_day_discharge') | float) + (states('sensor.battery_day_charge') | float)}}"
        device_class: energy
        state_class: total
        unit_of_measurement: kWh
```


Instead of "value_template" I used the "state" option and I disabled the "friendly_name" option, thanks!
