### DISCUSSION TITLE
Negative Solar Yield during the night

### DISCUSSION THREAD

**Discussion by graphistudio** [wlcrs/huawei_solar#461] [Setting up the integration]
I have a SUN2000-6KTL-L1 connected to a 6kw Luna battery pack.

using this code:

```
  - sensor:
      - name: energy_pv
        #friendly_name: "PV Energy"
        unique_id: "PV Energy"
        state: "{{ (states('sensor.inverter_total_yield') | float) - (states('sensor.battery_total_discharge') | float) + (states('sensor.battery_total_charge') | float)}}"
        device_class: energy      
        state_class: total
        unit_of_measurement: kWh
      - name: energy_pv_daily
        #friendly_name: "PV Energy daily"
        unique_id: "PV Energy daily"
        state: "{{ (states('sensor.inverter_daily_yield') | float) - (states('sensor.battery_day_discharge') | float) + (states('sensor.battery_day_charge') | float)}}"
        device_class: energy
        state_class: total
        unit_of_measurement: kWh
```

The energy dashboard create this graph:

[
![](https://community-assets.home-assistant.io/original/4X/7/5/e/75e33e05d5c0df923de0e8ec07a6fc9975d156e7.png)
](url)
But as you can see there is a negative solar production during the night.

How can I solve this issue?
