### DISCUSSION TITLE
Daily Solar Yield - Input Power with Efficiency Loss

### DISCUSSION THREAD

**Discussion by Roving-Ronin** [wlcrs/huawei_solar#484] [General]
Just looking at the 'Input Power with Efficiency Loss' calculation at: https://github.com/wlcrs/huawei_solar/wiki/Daily-Solar-Yield#a-better-approach and thinking that this rather rough in its calculation, given its only using arbitrary weightings (98% / 95% / 90%). Thinking that since the integration provides access to the actual efficiency ratings of the inverter(s) that this sensor could be better calculated by calling the input power of the inverter and applying the actual / live efficiency rating of the inverter (as the inverter is calculating at that moment).

Throwing it out there for feedback and suggestions if this sensor would be more accurate if it was calculated using the following, instead of the version at the above URL:

```
  # Shows 'Daily Solar Yield' being the yield of your solar panels, minus any efficiency losses by the inverter
  # See: https://github.com/wlcrs/huawei_solar/wiki/Daily-Solar-Yield
  - sensor:
    - name: "Inverters Input Power with Efficiency Loss"
      unique_id: inverters_input_power_with_efficiency_loss
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      state: >
        {% set inverter1_input_with_efficiency_loss = (states('sensor.inverter_efficiency_1') | float(0) /100) * states('sensor.inverter_input_power_1') | float(0) %}
        {% set inverter2_input_with_efficiency_loss = (states('sensor.inverter_efficiency_2') | float(0) /100) * states('sensor.inverter_input_power_2') | float(0) %}
        {{ (inverter1_input_with_efficiency_loss + inverter2_input_with_efficiency_loss) | round(2) }}
```
Note: Each inverter is calculated individually to ensure maximum accuracy, verses multiplying the combined input power by an averaged efficiency rating (that would also be open to error if one inverter is operating below efficiency, in which case the average efficieny would give an incorrect reading for the other inverter(s) in a cascade.

Also would users prefer to see a sensor for each inverters' input power with efficiency loss and then a seperate sensor that sums up the total of the individual inverters efficiency with loss, that would allow seeing the individual outputs and recording their individual statistics (in case of needing to fault find etc) in addition to the sensor showing the sum of all inverters (to use in dashboards etc) ?

Tagging some people who have shown interest in this sensor before: 
@JohnMcLear 
@graphistudio
@heinemannj
