### DISCUSSION TITLE
trying to get my solar production to show

### DISCUSSION THREAD

**Discussion by rikrikrik** [wlcrs/huawei_solar#518] [Setting up the integration]
sensor.inverter_active_power doesn't turn up on the list on http://homeassistant:8123/config/energy

any advice?

**Comment by Roving-Ronin** [comment]
@rikrikrik have you read the Wiki and in particular the sections re sensors, dashboards etc.
https://github.com/wlcrs/huawei_solar/wiki/Daily-Solar-Yield
https://github.com/wlcrs/huawei_solar/wiki/Dashboards
https://github.com/wlcrs/huawei_solar/wiki/Defining-custom-sensors
https://github.com/wlcrs/huawei_solar/wiki/Visualisations

Here's some examples, from my setup (I have 2 inverters and manually change the sensor names to make more sense.. i.e. inverter1 / inverter2).

Yaml that adds derived sensors from the inverters, gives overall totals etc.

```
template:

#############################
#   
#   WLCRS - Huawei Solar Integrattion - Combine multiple inverter values
#   See: https://github.com/wlcrs/huawei_solar/wiki/Connecting-to-daisy-chained-inverters
#
#   If your HA instance has a /config/packages directory configured, this may be deployed by saving this text into a file
#   in that location. i.e.   /config/packages/huawei_derived_sensors.yaml
#

  # Shows the combined current production of all inverters, in Watts
  - sensor:
    - name: "Inverters Input Power"
      unique_id: inverters_input_power
      unit_of_measurement: "W"
      device_class: "power"
      state_class: measurement
      state: "{{ (states('sensor.inverter1_input_power') | float) + (states('sensor.inverter2_input_power') | float)}}"

  # Shows 'Daily Solar Yield' being the yield of your solar panels, minus any efficiency losses by the inverter
  # See: https://github.com/wlcrs/huawei_solar/wiki/Daily-Solar-Yield
  - sensor:
    - name: "Inverters Input Power with Efficiency Loss"
      unique_id: inverters_input_power_with_efficiency_loss
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      state: >
        {% set inverter1_input_with_efficiency = (states('sensor.inverter1_efficiency') | float(0) /100) * states('sensor.inverter1_input_power') | float(0) %}
        {% set inverter2_input_with_efficiency = (states('sensor.inverter2_efficiency') | float(0) /100) * states('sensor.inverter2_input_power') | float(0) %}
        {{ (inverter1_input_with_efficiency + inverter2_input_with_efficiency) | round(2) }}

  # Shows the combined current battery capacity, as percentage
#  - sensor:
#    - name: "Batteries State of Capacity"
#      unique_id: batteries_state_of_capacity
#      unit_of_measurement: "%"
#      device_class: "battery"
#      state_class: measurement
#      state: "{{ (((states('sensor.battery1_state_of_capacity') | float) + (states('sensor.battery2_state_of_capacity') | float))/2) | round(2)}}"

  # Shows the combined current battery charge / discharge power, in Watts
#  - sensor:
#    - name: "Batteries Charge Discharge Power"
#      unique_id: batteries_charge_discharge_power
#      unit_of_measurement: "W"
#      device_class: "power"
#      state_class: measurement
#      state: "{{ (states('sensor.battery1_charge_discharge_power') | float) + (states('sensor.battery2_charge_discharge_power') | float)}}"

  # Shows the combined daily production of all inverters, in kWh. Max 0 is to stop it reporting negative numbers.
  - sensor:
    - name: "Inverters Total Daily Yield"
      unique_id: inverters_total_daily_yield
      unit_of_measurement: "kWh"
      device_class: "energy"
      state_class: total_increasing
      # total used instead of total_increasing in case of negative yield on L1 / M1 inverters overnight
      state: "{{ [ states('sensor.inverter1_daily_yield') | float + (states('sensor.inverter2_daily_yield') | float) | round(3), 0 ]|max }}"

  # Shows the combined current Active Power of all inverters, in Watts
  - sensor:
    - name: "Inverters Active Power"
      unique_id: inverters_active_power
      unit_of_measurement: "W"
      device_class: "power"
      state_class: measurement
      state: "{{ (states('sensor.inverter1_active_power') | float) + (states('sensor.inverter2_active_power') | float)}}"

  # Shows the calculated current load, in Watts
  - sensor:
    - name: "Power Meter Active Load"
      unique_id: power_meter_active_load
      unit_of_measurement: "W"
      device_class: "power"
      state_class: measurement
      state: "{{ ( (states('sensor.inverters_active_power') | int ) - (states('sensor.power_meter_active_power') | int )) }}"

#############################
```

This YAML below defines the utility meters (I actually use the Energy Meter customisation, that adds the ability for the meter to calculate the power costs for themselves, see - https://github.com/zeronounours/HA-custom-component-energy-meter ), using this you can then end up with a Peak/Shoulder/OffPeak sensor (and costs) that you can add into the Energy Dashboard, as you appear to be trying to. Peak is based on Mon-Fri 7am-9am and 5pm - 8pm, Shoulder is 9am-5pm and 8pm-10pm and Off Peak is weekends after 10pm - 7am and all weekend.  If you need to change the hours you should be able to easily work it out and the Rates $.

```
# Updated 1 July 2023 for new Red Energy Rates
# Updated 1 October 2023 for new Red Energy Rates

template:
  - sensor:

#  Current_Price_RedEnergy_TOU provides a backup method to allow selecting the 'Use an entity with current rate' in Energy Dashboard.
#  If you set the prices here, remember to ALSO set them in the 'electricity_import_rate_???' and daily supply charge sensors.

    - name: "Electricity - Price" 
      unique_id: electricity_price
      unit_of_measurement: "$/kWh"
      device_class: monetary
      state:  "
        {%set Peak = 0.42790 %}
        {%set WeekdayShoulder = 0.36498 %}
        {%set OffPeak = 0.27698 %}
        {%set H = as_timestamp(now())|timestamp_custom ('%-H')|float(0) %} {##Hour (24-hour clock) as a decimal number. 0, 1, 2, ... 23##}
        {%set w = as_timestamp(now())|timestamp_custom ('%w')|float(0) %} {##HWeekday as a decimal number, where 0 is Sunday and 6 is Saturday.	0, 1, …, 6##}	 
        {##0 for weekday, 1 for weekend##}
        {% if (w == 0) or  (w == 6) %} {% set weekday = 0 %}
        {% else %} {% set weekday = 1 %}
        {% endif %}
        {% set charge = 0 %}
        {##peak##}
        {% if (weekday == 1) and (H >= 7) and (H < 9) %} {{Peak}}
        {% elif (weekday == 1) and (H >= 17) and (H < 20) %} {{Peak}}
        {##weekday shoulder##}
        {% elif (weekday == 1) and (H >= 9) and (H < 17) %} {{WeekdayShoulder}}
        {% elif (weekday == 1) and (H >= 20) and (H < 22) %} {{WeekdayShoulder}}
        {##off peak##}
        {% else %} {{OffPeak}}
        {% endif %}
        "

#########################
#
# ALTERNATIVE VERSION TO ABOVE TOU
#

#- platform: template
#    sensors:
#      your_tariff:
#        friendly_name: My Tariff
#        unit_of_measurement: '$/kWh'
#        value_template: >
#          {% set tariff = { "Peak": 0.42790, "Shoulder": 0.36498, "OffPeak": 0.27698 } %}
#          {% set time = { "month": (now().strftime('%m') | int), "hour": (now().strftime('%H') | int), "weekday": (now().weekday() | int ) } %}
#          {%if (time.hour > 21) or (time.hour < 7) %}
#              {{ tariff.OffPeak }}
#          {%elif ((time.month > 10) or (time.month < 4)) and (time.weekday < 5) and ((time.hour > 13) and (time.hour < 20)) %}
#              {{ tariff.Peak }}
#          {%elif ((time.month > 5) and (time.month < 9)) and (time.weekday < 5) and ((time.hour > 16) and (time.hour < 21)) %}
#              {{ tariff.Peak }}
#          {%else%}
#              {{ tariff.Shoulder }}
#         {%endif%}
#

####################################
# IMPORT UTILITY METERS
#

#utility_meter:
energy_meter:

  hs_power_imported_daily:
    unique_id: hs_power_imported_daily
    name: HS Power Imported - Daily
    source: sensor.power_meter_consumption
    cycle: daily
    price_entity: &entity-price sensor.electricity_price
    tariffs:
      - peak
      - shoulder
      - offpeak

  hs_power_imported_monthly:
    unique_id: hs_power_imported_monthly
    name: HS Power Imported - Monthly
    source: sensor.power_meter_consumption
    cycle: monthly
    price_entity: *entity-price
    tariffs:
      - peak
      - shoulder
      - offpeak

  hs_power_imported_yearly:
    unique_id: hs_power_imported_yearly
    name: HS Power Imported - Yearly
    source: sensor.power_meter_consumption
    cycle: yearly
    price_entity: *entity-price
    tariffs:
      - peak
      - shoulder
      - offpeak


#########################
# EXPORT ENERGY METERS
#

  hs_power_exported_daily:
    unique_id: hs_power_exported_daily
    name: HS Power - Exported Daily
    source: sensor.power_meter_exported
    cycle: daily
    price: 0.07

  hs_power_exported_monthly:
    unique_id: hs_power_exported_monthly
    name: HS Power - Exported Monthly
    source: sensor.power_meter_exported
    cycle: monthly
    price: 0.07

  hs_power_exported_yearly:
    unique_id: hs_power_exported_yearly
    name: HS Power - Exported Yearly
    source: sensor.power_meter_exported
    cycle: yearly
    price: 0.07


#########################
#
# GROUP - TO SUM UP THE DAILY / MONTHLY / YEARLY IMPORT KWH and $ SENSORS
#         TO GIVE A TOTAL OF EACH
#

sensor:

# DAILY
  - platform: group
    name: HS Power Imported - Daily Total kWh
    unique_id: hs_power_imported_daily_total_kwh
    type: sum
    entities:
      - sensor.hs_power_imported_daily_peak
      - sensor.hs_power_imported_daily_shoulder
      - sensor.hs_power_imported_daily_offpeak

  - platform: group
    name: HS Power Imported - Daily Total Cost
    unique_id: hs_power_imported_daily_total_cost
    type: sum
    entities:
      - sensor.hs_power_imported_daily_cost_peak
      - sensor.hs_power_imported_daily_cost_shoulder
      - sensor.hs_power_imported_daily_cost_offpeak

# MONTHLY
  - platform: group
    name: HS Power Imported - Monthly Total kWh
    unique_id: hs_power_imported_monthly_total_kwh
    type: sum
    entities:
      - sensor.hs_power_imported_monthly_peak
      - sensor.hs_power_imported_monthly_shoulder
      - sensor.hs_power_imported_monthly_offpeak

  - platform: group
    name: HS Power Imported - Monthly Total Cost
    unique_id: hs_power_imported_monthly_total_cost
    type: sum
    entities:
      - sensor.hs_power_imported_monthly_cost_peak
      - sensor.hs_power_imported_monthly_cost_shoulder
      - sensor.hs_power_imported_monthly_cost_offpeak

# YEARLY
  - platform: group
    name: HS Power Imported - Yearly Total kWh
    unique_id: hs_power_imported_yearly_total_kwh
    type: sum
    entities:
      - sensor.hs_power_imported_yearly_peak
      - sensor.hs_power_imported_yearly_shoulder
      - sensor.hs_power_imported_yearly_offpeak

  - platform: group
    name: HS Power Imported - Yearly Total Cost
    unique_id: hs_power_imported_yearly_total_cost
    type: sum
    entities:
      - sensor.hs_power_imported_yearly_cost_peak
      - sensor.hs_power_imported_yearly_cost_shoulder
      - sensor.hs_power_imported_yearly_cost_offpeak


#######################
#
# Checks the time and based upon TOU rate times, updates the 'hs_power_imported_daily/monthly/yearly' entities to use Peak / Shoulder / OffPeak tariff
#

automation:
### adjust the time triggers below to match when your standard electricity tariff changes (peak, shoulder, offpeak). Adjust the template in the action block as required to match your plan.
  - alias: Set Electricity Tariff
    description: 'Set Electricity Tariff (Huawei Solar) depending upon the day of week and time'
    trigger:
      - platform: time
        at: '07:00:30'
      - platform: time
        at: '09:00:30'
      - platform: time
        at: '17:00:30'
      - platform: time
        at: '20:00:30'
      - platform: time
        at: '22:00:30'
      - platform: homeassistant
        event: start
    condition: []
    action:
      - service: select.select_option
        data:
          option: >-
            {% set t = now() %}
            {%- if (( t.hour >= 7 and t.hour < 9 ) or ( t.hour >= 17 and t.hour < 20 )) and
            is_state('binary_sensor.workday_sensor', 'on') %}
              peak
            {%- elif (( t.hour >= 9 and t.hour < 17 ) or ( t.hour >= 20 and t.hour < 22 )) and 
            is_state('binary_sensor.workday_sensor', 'on') %}
              shoulder
            {%- else -%}
              offpeak
            {%- endif -%}
        target:
          entity_id:
#  Selectors used by utility_meter / energy_meter
            - select.hs_power_imported_daily
            - select.hs_power_imported_monthly
            - select.hs_power_imported_yearly
    mode: single

#######################
```

My Energy Dash looks like this... ( note the 2 x ' Daily Yield' are the individual 2 x 6kW M1's I run... I just haven't needed to rename them for the dash view).

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/94d6f176-19fa-4630-ae7f-3a1e9a2ffd32)

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/3b7ac428-cbc1-47ea-b114-5bcaa6352d4b)

Entries used to setup the dash are:
![image](https://github.com/wlcrs/huawei_solar/assets/108674933/bea3fa75-499f-4d46-ae68-663bcdd32abf)

With the Energy Meter addon each time period / billing rate has its own daily cost tracker (and the config also defines a sensor for the total cost per day.
![image](https://github.com/wlcrs/huawei_solar/assets/108674933/709f2ec0-7233-4070-9280-0e43a32e3501)


BTW: "HS" in the sensor names is just my own change to name the sensors with a prefix reflecting "Huawei Solar", given I also have IoTaWatt and SolarAnalytics sensors tracking power / solar data in my HA.
