### DISCUSSION TITLE
Correct Riemann Sum "version" for calculating solar power yield?

### DISCUSSION THREAD

**Discussion by SvenAbels** [wlcrs/huawei_solar#524] [General]
As mentioned in the FAQ, the calculation of solar power generated during a day can be calculated with the FAQ example  taking account the efficiency loss in the inverter.  In this example, a Riemann Sum is used.

When setting up a Rieman Sum in Home Assistant 3 different types can be used: trapezoid, left and right.   I tired out all 3 versions and indeed they lead to slightly different values over the day. 

The FAQ example defines the riman sum using the config.yml instead of using the Home Assistant template menu and  it does not specify which version of Rieman is used in this case.

So I wonder: 
-Which one is used in the FAQ example?
-Which one makes most sense for estimating the solar power yield of a day?

**Comment by Roving-Ronin** [comment]
@SvenAbels 

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/ae7f7e1b-e74d-48e5-ad0f-8bb6cb332b27)

Personally instead of using hard coded efficiency percentages in the yaml formula, the code below uses the actual efficiency data as provided by the inverter (at that moment). Code below is also for 2 inverters setup in a cascade, amend if you only have 1 (or more).

```
  # Shows 'Daily Solar Yield' being the yield of your solar panels, minus any efficiency losses by the inverter
  # See: https://github.com/wlcrs/huawei_solar/wiki/Daily-Solar-Yield
  - sensor:
    - name: "Inverters Input Power with Efficiency Loss"
      unique_id: inverters_input_power_with_efficiency_loss
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      state: >
        {% set inverter1_input_with_efficiency = (states('sensor.inverter1_efficiency') | float(0) /100) * states('sensor.inverter1_input_power') | float(0) %}
        {% set inverter2_input_with_efficiency = (states('sensor.inverter2_efficiency') | float(0) /100) * states('sensor.inverter2_input_power') | float(0) %}
        {{ (inverter1_input_with_efficiency + inverter2_input_with_efficiency) | round(3) }}

```
