### DISCUSSION TITLE
[Feature Request]: EV charging drains LUNA2000 battery empty.

### DISCUSSION THREAD

**Discussion by johanvh83** [wlcrs/huawei_solar#625] [General]
### Describe your feature request

I own a Huawei converter and LUNA2000 battery. Your integrations works already for months without any problem. Apologies!
Recently I got a company eletrical vehicle (EV).
At daytime the home battery is charged by the solar panels. I want to use the stored energy for my home usage and most preferable when I have to pay the most for the energy, so during day time.
The charging of the EV is managed by the Engie Drive app. It starts the charging when the night - low tariff starts.
In the area where I live in Belgium, it's 21:00.
I realised that the EV drains quickly the home battery empty. As a result, the day after, I have to pay day high tarriff for my personnal home use! I did an investment into the home battery but due to the EV charging I don't get any profit!
Is it possible to 'disable the discharge to the home battery' in order to keep the storaged energy till the morning after?
The charging of my car should come from the grid, not from the home battery. 

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration

**Comment by Roving-Ronin** [comment]
@johanvh83 are you saying you use your LUNA battery during the day, when normally people are running of the solar panel output to power the house and also recharge the battery, because they used the battery overnight (when most countries charge higher prices for electricity) ?

If so, I think it would be best to look at the Huawei manual and refer to the Time of Use (TOU) settings, you can then configure the TOU scheduled (iirc I think you can have 5-6 dirrent time period you can manually define in the Huawei software).

**Comment by johanvh83** [comment]
No, apologies if my post wasn't clear. 
No, I use the system as you describe. During the day, the battery is charged by the solar panel if the power consumption of the home is less compared to the produced solar energy. During daytime my home consumption is normally very low (approx 300 W).

Would the TOU setting solve my problem? The only thing I'd like to do is keep the stored energy in the home battery for my own home use instead of use the stored energy to charge the EV.

I guess TOU is used to charge the battery from the grid in nighttime and use the stored energy at daytime
https://support.huawei.com/enterprise/en/doc/EDOC1100186676/e8d2e6db/tou-time-of-use-mode

Checked all HA services for the Huawei Solar integration but don't believe I'm able get the result I want

**Comment by wlcrs** [comment]
You can set the maximum discharge power to 0 to disable discharging.

**Comment by johanvh83** [comment]
Thys, thanks for your answer. Is it possible to integrate this feature in your integration? If I'm not mistaken I don't see any service to set the maximum discharge power to 0 in Home Assistant.
Or do I have to use 'Huawei Solar: Forcible Discharge' and set Power - Wattage used for the discharge to 0?

**Reply by lakatusch** [reply]
hi Johan,
i have also sun2000 and luna2000...

i do exactly what you want : set number.battery_maximum_discharging_power to 0, when "car-power" > 0.

And, you have to switch back, set number.battery_maximum_discharging_power to 5000, when "car-power" =0

number.battery_maximum_discharging_power is available in HA via Fusion ingetration...

but, you need the value of "car-power", meaning the power consumption of your wallbox... 

Or, maybe your car delievers the status of being charged via another HA integration... you didnt post your car... for my Cupra Born, there is a HA integration in which is displayed, if the car is charging or not... but, please remember, in this solution, you would set dischargopower to 0 also when you are on journey and you load at a public wallbox...

**Reply by lakatusch** [reply]
EDIT:
additional to this... i use evcc to handle the wallbox https://github.com/evcc-io/evcc

**Reply by Roving-Ronin** [reply]
@johanvh83 

In HA this is not a function of the integration, this is something that YOU do using automations. Assuming you have a method of detecting the Active Power (Watts) being used on the EV charger, then you'd do something like;

```
alias: Huawei Battery - Disable Discharge if EV Charger 250W+
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.name-of-the-sensor-detecting-ev-charger-active-power
    for:
      hours: 0
      minutes: 3
      seconds: 0
    above: 500
condition: []
action:
  - if:
      - condition: numeric_state
        entity_id: name-of-the-sensor-detecting-ev-charger-active-power
        above: 500
    then:
      - device_id: <device_id_of_Luna_Batery>
        domain: number
        entity_id: <Set Action - Set Value for Battery Maximum discharging power>
        type: set_value
        value: 0
    else:
      - device_id: <device_id_of_Luna_Batery>
        domain: number
        entity_id: <Set Action - Set Value for Battery Maximum discharging power>
        type: set_value
        value: 5000
mode: single

```

This needs validation for the logic etc and working out any other conditions that need to be set, as above translates to "If the EV Charger Active Power is above 500W for more than 3 minutes then set Battery Discharge Power to 0W, ELSE set Battery Discharge Power to 5000W (or 2500W if you don't have a 15kWh LUNA)'. So given this you could be charging your EV at night and the battery will stop discharging for the house, ALL power will be imported from the grid and you'll only go back to running the house from the LUNA when the EV finishes.

**Reply by spelzl** [reply]
Does the battery maximum **dis**charge power value need to be set as negative, e.g. -2500 or as positive, e.g. 2500 value?

**Comment by johanvh83** [comment]
Hi, still in the learning curse, and so far no time to do things.
Yesterday I just used the develloper tools in HA to set the discharge power to 0 to see the behaviour today.
Weather wasn't great in Belgium so my battery charged up to 28% and remained there. All power came from the grid when the sun disapperead, so that worked as suspected.
Few minutes ago it was my intention, because I don't have to charge the EV, to use the stored battery power for my home use.
So I used the same service 'Huawei Solar: Forcible Discharge' and changed the power to 5000 instead of 0.
I was very surprised that after some seconds 5000 W was discharged from the batttery and fed into the grid!
No idea why and how to get the original situation?

**Reply by lakatusch** [reply]
I wrote
set number.battery_maximum_discharging_power to 5000

You wrote
Huawei Solar: Forcible Discharge' and changed the power to 5000

Conclusion 
Forcible discharge  ! = maximum discharge

**Reply by HolgerMiara** [reply]
Hi @johanvh83 

I fully understand your confusion! There are a number of services for the Huawei battery, but you won't find any service to set  
number.battery_maximum_discharging_power. 

If you -- just like myself -- click your automations together in the visual editor, then do the following under "**Add Action**"
--> **Device** --> **choose your battery** --> **choose "Set value for Battery Maximum discharging power"** --> **choose "0"** during charging of your car and reset to whatever you prefer after charging has completed. The result is somehow hard to read in YAML, in my case it looks like this:
```
device_id: 90d86b4b44627857995f1e77853f
domain: number
entity_id: d3137525a55c1b2bf58cbcec78dc
type: set_value
value: 0
``` 

Alternatively, you could probably change the value with with a service call like this:
```
service: number.set_value
metadata: {}
data:
  value: "0"
target:
  entity_id: number.battery_maximum_discharging_power
enabled: true
``` 
Cheers and good luck ;-)

**Reply by johanvh83** [reply]
@HolgerMiara thanks for your clarification. I didn't know automations could be used to set a numeric entity. Great. Thank you very much.

**Reply by spelzl** [reply]
Hi @HolgerMiara ,
I'd like to learn how I can create an editable dashcard for the entitiy number.battery_maximum_discharging_power.
It happens that once I added the entity to a dashboard card it becomes unavailable after a reboot.
Can you help me please?

**Reply by HolgerMiara** [reply]
Hi spelzl, 
I am no hero in dashboards at all, but have you tried opening the dashboard in which you would like to add the card, click on the pencil in the upper right corner, click on the blue "+ ADD CARD" button in the lower right corner, find and click on "Entity" card and insert in the "Entity*" field in the top left "number.battery_maximum_discharging_power". Then "Save" and thereafter "Done" in the top right. 
Does that help?

**Reply by spelzl** [reply]
@HolgerMiara

![image](https://github.com/wlcrs/huawei_solar/assets/82170464/6abef52e-e078-4918-b280-3cbf2123126b)

It appears as if it wasn't available.
Neither in the entity dashcard nor in the developer tool.
I wonder how its status can be visualized and set in a dashcard?

@Roving-Ronin any suggestion you could provide?

**Reply by johanvh83** [reply]
@spelzl, I'm not a programmer so I can't help you but I would recommend you to open a post in the HA community or on Discord. Much more chance to get a solution instead of here where I opened a ticket and you are asking for a solution out of scope of my initial question/thread.

**Reply by spelzl** [reply]
@johanvh83 what is the name of the discord channel?

**Comment by johanvh83** [comment]
Which service should I use? I don't have a command prompt...

**Reply by lakatusch** [reply]
Home assistant
Settings
Devices services
Huawei solar
3 devices
Battery

Then under configuration
Maximum discharge power

**Comment by johanvh83** [comment]
Thanks for your help but I never changed this setting. 
I checked and it is set to 5000 W.
How can I go back to the original settings?
Again: the only thing I did: use service 'Huawei Solar: Forcible Discharge' and set Powe to 0.
When I set it back to 5000. All stored power in the battery is fed into the grid.

**Reply by Roving-Ronin** [reply]
@johanvh83 

Forible discharge service is where you want to force the battery to dump to the grid. 
i.e. You have another integration providing you with the current market EXPORT price per kWh and it suddenly changes to say 'Export Compensation = $20 per pWh', you would then setup an automation that says when 'Export Compensation' equals or is greater than (say) $5 per kWh, then call the  'Huawei Solar: Forcible Discharge' service and dump at 5000W (or alternatively call the Discharge to SoC% service and say discharge to x%... leaving enough for your own planned nightly requirements).

You then also need to setup an automation that then turns off the 'Forcible Discharge' settings, when something triggers it, such as 'If Export Compensation drops below $0.20 per kWh then revert/disable'.

See answer above re the way you need to go about changing battery settings to ensure the EV charger doesn't drain in and instead works off the grid power.

**Comment by johanvh83** [comment]
@lakatusch first off all, thanks for your input! I finally found some time to continue.
I've checked and installed https://github.com/tijsverkoyen/HomeAssistant-FusionSolar 
During first startup it asks to install 'Kiosk' or 'OpenAPI'. I guess I have to go for the OpenAPI option and need some additional information from my installer. My installer gave me installers rights so I believe I must be able to retrieve the required data.
When I got to System -> Company Management from the Main menu, I don't have an option 'Northbound management'.

This does mean you run both wlcrs's integration and the FusionSolar integration? wlcrs isn't able to add this feature? It would save the effort but also processor resources and diskspace. 

FYI, I own a VW ID4 and an Easee wall charger. The wall charger has many intities so that's a good source and reliable, much better than the car's integration.

**Reply by Roving-Ronin** [reply]
@johanvh83 
Umm how do we jump from WLCRS integration to FusionSolar? The later is an alternative to WLCRS, and is not as good as the WLCRS integration. Basic thing is that FusionSolar is reliant upon the clount and having an API account enabled by Huawei Support to work, it also only updates something like every 5min (at best) versus every 30 seconds that WLCRS does (and does via local modbus queries).

As Thijs (WLCRS developer) mentioned above you can do what you want to do. Have you also read this https://github.com/wlcrs/huawei_solar/discussions/625#discussioncomment-8574890 that provides details on how to do what your attempting?

re Easee wall charger, a quick search reveals it also has an integration https://github.com/nordicopen/easee_hass  and thread https://github.com/jonasbkarlsson/ev_smart_charging/issues/46#issuecomment-1773720869 that you could use for obtaining additional information to use in automations etc.

**Comment by spelzl** [comment]
Does the battery maximum **dis**charge power value need to be set as negative, e.g. -2500 or as positive, e.g. 2500 value?

**Reply by johanvh83** [reply]
Positive value

**Comment by Roving-Ronin** [comment]
5kWh LUNA =  2500W
15kWh LUNA =  5000W
2 x 15kWh LUNA = 10000W

Set max charge a little lower, i.e. 4500W to keep it a bit cooler and the battery cells last longer.

**Comment by johanvh83** [comment]
According @wlcrs I have to set the maximum discharge power to 0 to disable discharging.
This can be set in Home assistant -> Settings -> Devices services -> Huawei solar -> 3 devices -> Battery
Then under configuration -> Maximum discharge power
As far as I know this is a manual setting and cannot be used in automations. So not usefull.
The integration has this data. @wlcrs would it be possible to add an extra service to set this entity please?

**Reply by lakatusch** [reply]
I use the value in automations...

**Reply by johanvh83** [reply]
Are you able to post your automation here?

**Reply by lakatusch** [reply]
![20240225_190903](https://github.com/wlcrs/huawei_solar/assets/18687119/5b211a68-ff5c-4620-939c-5d1bd3c58a15)

**Reply by Roving-Ronin** [reply]
@johanvh83 please ensure that you take time to read the thread, that people are spending time trying to help you with your issue. It has been pointed out that this is done with an automation, and not a service, and the yaml code for doing this has been provided previously, allowing you to copy and paste it into a blank automation and then just update with your specific device IDs.

As above:

```
alias: Huawei Battery - Disable Discharge if EV Charger 250W+
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.name-of-the-sensor-detecting-ev-charger-active-power
    for:
      hours: 0
      minutes: 3
      seconds: 0
    above: 500
condition: []
action:
  - if:
      - condition: numeric_state
        entity_id: name-of-the-sensor-detecting-ev-charger-active-power
        above: 500
    then:
      - device_id: <device_id_of_Luna_Batery>
        domain: number
        entity_id: <Set Action - Set Value for Battery Maximum discharging power>
        type: set_value
        value: 0
    else:
      - device_id: <device_id_of_Luna_Batery>
        domain: number
        entity_id: <Set Action - Set Value for Battery Maximum discharging power>
        type: set_value
        value: 5000
mode: single

```
