### DISCUSSION TITLE
Sunsynk Power Flow Card for Huawei (WLCRS)

### DISCUSSION THREAD

**Discussion by Roving-Ronin** [wlcrs/huawei_solar#632] [Show your dashboards!]
Moving the discussion from https://github.com/wlcrs/huawei_solar/pull/631

Yes that is what I am doing currently, so all users of WLCRS can add the SunSynk card in HACS, then go to the documentation site https://slipx06.github.io/sunsynk-power-flow-card/examples/huawei.html and choose from 1 of 5 examples (combinations of 1phase or 3phase inverters with 1 or 2 inverters and 1 or 2 batteries) and copy the yaml into the card on the HA dashboard, then place two files into your packages directory that have the derived sensors.

These derviced sensors have the logic built into them so that if you don't have a battery(s) or only 1 string etc they won't cause your HA to stop, at worst they'll have a (!) icon in the entities list and if that bothers you can you just disable them. At least this means there's ONE version of the sensors file that works for everyone (I was originally writing 4 versions and then thought ...what the xxxxx).

The other file is one with some default example sensors (actually my GPO for the UPS with all my servers and another for the Network Kit in my place, given they are the biggest constant draw). Instead of using the AUX to show generators by default I've used that to show two major users of power (the green boxes above the house icon) that then show their combined Active Power and above that their Daily  kWh usage. 
For Non-Essential Load I've used my HVAC, Oven and Clothes Dryer (if you have a battery you can only show 2 though, due to space on the card), with these summing up their draw. Basically when finished you just need to modify the AUX and Non-Essential groups created in HA to contain the devices you have/want to monitor and then you end up with it working out their Active Power, and from that deducting that so the purple box (Active Power into house)  reflects the total less these others that are already shown .

Note: The colours can be changed. The thickness of the lines from the PV to Inverter / Inverter to Battery / To Grid is proportional, i.e. more active kW then it is thicker.  The battery outline changes colour to reflect its' status and/or the source of energy when charging. The house changes colour proportionally to show the source of its power (i.e. will be 50/50 yellow and red, if powering from solar and grid). The 'balls' on the lines move in the direction of the power flow and move faster/slower based on the volume.

Examples:

2 x L1 5kW (1 phase) Inverters with 1 x 15kWh LUNA S0 ESS - System currently charging and importing (58W) from the grid.

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/382929ab-cc6a-45ea-a586-fd779b4947ba)

Battery fully charged and floating, whilst excess kW are exported to the power grid.
![image](https://github.com/wlcrs/huawei_solar/assets/108674933/950affbf-465c-47c0-b1ee-db8f807df4e0)

______________________________________________

2 x M1 6kW (3 phase) Inverters with NO battery - System currently producing and exporting to the grid.

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/9950b1c4-f52c-4aca-ba9e-3ecaa3a79c65)

**Comment by spelzl** [comment]
Yiehpiehyeah!
Great!
Thank you so much!

**Reply by Roving-Ronin** [reply]
The examples I will be using also make use of the energy_monitor integration, that allows easily adding what would normally be a utility_meter (to get all the daily/weekly/monthly/yearly kWh import / export etc totals) but it also allows pulling the import / export price at that moment and applying it to get 2 sensors for each data feed.. 1 for kWh and another showing the Cost/Compensation.

So you'll also need to install: https://github.com/zeronounours/HA-custom-component-energy-meter

**Reply by Roving-Ronin** [reply]
@spelzl @serbat - Graphics updated in OP.

**Reply by serbat** [reply]
super..... great job
this card is becoming very complete, maybe a few more user boxes would fit...

**Reply by Roving-Ronin** [reply]
Not for now, @slipx06 is hampered by space on the card, however hopefully he'll add a 'wide' option for the card in future.

**Reply by serbat** [reply]
Hopefully it would be really useful

**Reply by spelzl** [reply]
Is there a guide how to setup the card within HA, which I can forward to friend?

**Reply by Roving-Ronin** [reply]
@spelzl the documentation is at: https://slipx06.github.io/sunsynk-power-flow-card/index.html for how to configure it. In regards Huawei with WLCRS I still have to make up some example electricity cost yaml (with tariff plans and sensors that then publish the kWh cost to import or compensation if exporting), as these are then used to provide the sensors for Daily Consumed Buy/Sell and PV produced etc.

I've just submitted a pull request to merge the examples (minus the cost yamls) into the Sunsynk repository - https://slipx06.github.io/sunsynk-power-flow-card/examples/huawei.html that will probably be approved within the next 24hours. 

Pre-merged version (i.e. under development / testing etc) will be on my fork at https://github.com/Roving-Ronin/sunsynk-power-flow-card/tree/master/docs/examples/huawei_packages and issues / requests (in the discussion section) can be raised there, so we don't clutter up the Sunsynk discussion with 'development' Huawei questions/issues.

**Reply by spelzl** [reply]
Many thanks!
I will have a look at it first before bothering you and or my friend further.

**Reply by Roving-Ronin** [reply]
@spelzl 
I just uploaded a couple of Energy Cost yaml examples, one with Time of Use charging and the other flat rate. What kind of energy retail plans do you use (in which country) ?

**Reply by spelzl** [reply]
Well, I have in and out a static plan, i.e. pay 24,75€cent per kWh for consumption and get paid 8.2€cent for any kWh fed into the grid in Germany. Many nowadays change over to energy providers like tibber or aWattar for dynamic energy pricing.

**Reply by Roving-Ronin** [reply]
@spelzl so a flat rate plan, you can use the Synergy Energy plan then, just rename and update the Electricity Price and FIT rates and your good to go.

**Reply by spelzl** [reply]
I am not sure if we share the same understanding of what a flat rate is? My understanding of a flat rate is when you pay a fixed €-amount for a fixed (not to be exceeded) kWh-package - regardless if you consume less.
That is not what my contract is about. I pay per each kWh a fixed €cent price plus a monthly basic service fee.

**Reply by Roving-Ronin** [reply]
@spelzl 
Oh OK, in Australia the term 'Fixed Rate' means you pay per kWh but the rate you pay for it remains the same no matter the day of the week, or the time of the day. This is different that 'Time of Use' (ToU) that we have that charges differing rates per kWh depending upon when your using it (i.e. Peak = Highest Cost = periods of the morning and evening when most demand upon the Grid).....and due to having an fools in Government pushing 100% renewables the prices skyrocket and outages occur... instead of using all the nuclear materials we ship overseas and others then use for fueling power stations cheaply.
We also have ToU with DEMAND, where they are adding charging an additional fee for any kWh you use during Peak hours, based on the highest 30min kWh usage during peak of the month and multipled by a $0.xx rate and charged for every day of the month. And lastly new plans that are charging solar users for exporting during periods of the day and in same cases giving it to non solar users for free (Carl Marx would be proud).

From what your saying though.... "I pay per each kWh a fixed €cent price plus a monthly basic service fee." your on what we would call the flat rate tariff. What is your per kWh price to pull from the Grid ? Do you get paid anything per kWh to export to the grid ?

**Reply by spelzl** [reply]
@Roving-Ronin ,
yes, correct. It is identical to the flatr rate called in down-under.
As written above, my charge per kWh consumed is 24.75€cent and 8.2€cent per kWh supplied into the grid, i.e. 0.2475€ and 0.082€ respectively.

I have started to implement the sunsynk card. But haven't checked / corrected the entities, yet.

![image](https://github.com/wlcrs/huawei_solar/assets/82170464/402005f8-cb5c-4c3e-925f-29f81fddde10)

**Reply by Roving-Ronin** [reply]
@spelzl what is your inverter(s) and battery(s) setup ?  model / sizes.. Ah it looks like you have Solcast already installed... fyi for the 0 degree temp below the sun icon, you need to have some weather package installed and then update this line:

```
environment_temp: sensor.<your_location>_temp
```
to your actual sensor name.  Also don't overlook updating this line to the name of your grid or retail energy provide, or change it to null to just show 'Grid'.

```
grid:
  grid_name: Your-Grid-Name
```

D'Oh..note to self, you forgot to add in the list of extra WCLRS sensors that are off by default, and need to be enabled.

If looks like your using an M1 / 3 phase inverter, so in HA you also need to have all these sensors ENABLED. 
_____________________

**POWER METER:**

1 Phase
![image](https://github.com/wlcrs/huawei_solar/assets/108674933/bc46a0b2-3978-474f-b076-61f7d8928f81)

3 Phase
![image](https://github.com/wlcrs/huawei_solar/assets/108674933/69b899fe-d58c-4fac-92c5-2a407dfba81d)

_____________________

**INVERTER(S):**

1 Phase
![image](https://github.com/wlcrs/huawei_solar/assets/108674933/86d09e4e-8025-4ed3-8cb4-456a587efbcc)

3 Phase
![image](https://github.com/wlcrs/huawei_solar/assets/108674933/8f85a200-f441-4b96-aa2a-a25e6df1f22c)

Sorry its 1:30am where I am.. so my inverters are in standby, hence all the 0W.
_____________________

**BATTERY(S):**

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/b227ea4f-406f-46ce-b49c-ffcb572e2464)

Ignore the 'Battery 2 Temperature' unless you have 2. Just noticed that, its new.. hopefully WLCRS adds the temp sensor by default and make that only appear if a 2nd battery is installed.
_____________________

**Note:** If you have a LUNA ESS battery(s) you also need to update the WLCRS sensor.py file to add the custom sensors to show the battery temperature.  This needs to be repeated EVERY time that an updated version of WLCRS is installed/updated on your HA !

If you have a battery, please add a 'I need this sensor added by default' type comment to this pull request with WCLRS: https://github.com/wlcrs/huawei_solar/pull/631

To save people trying to work out how to do this, I've patched the v1.3.2 sensor.py with the extra temperature sensors and you can download it here https://github.com/Roving-Ronin/huawei_solar/blob/main/sensor.py  and place it into your /homeassistant/custom_components/huawei_solar director (rename the default one first i.e. sensor.v1-3-2 ) and then Reboot HA to reload WLCRS.

**Reply by Roving-Ronin** [reply]
@spelzl  Looks like this electricity yaml file would serve your needs.   These Electricity sensors can also be used in the HA Energy Dashboard, where you have the option of  'Select how HA should keep track of the costs of the consuming (and exported) energy', where you can choose 'Use an entity with current price' and these, or else choose the 'HS Grid - Imported Daily Cost' utility/energy meter that this code also creates as the 'Use an entity tracking the total costs'.

```
template:
  - sensor:

#
#  Grid Import 24x7   : $0.2475 p/kWh.
#  Grid Export (FIT)  : $0.082 p/kWh.
#
# This sensor says if the power_meter_active_power is <=0 (Importing from Grid) then the sensor reports the RATE1 price
# Alternatively if the power_meter_active_power >0 (Exporting to Grid) then the sensor reports the RATE2 price, that is set to ZERO.
# This allows the electricity_price sensor to then be used as a source to calculate things like 'How much did the HVAC cost' that reflects
# the HVAC using power that can change between paid for grid power, and free power from your solar plant.
#
    - name: "Electricity - Price" 
      unique_id: electricity_price
      unit_of_measurement: "€/kWh"
      device_class: monetary
      state: >
        {## Enter cost per kWh rates below. Rate 1 ##}
        {% set rate1 = 0.2475 %}
        {% set rate2 = 0.0 %}
        {% set power_meter_active_power = states('sensor.power_meter_active_power') | float %}
        {% if power_meter_active_power <= 0 %} {{rate1}}
        {% else %} {{rate2}}
        {% endif %}

#  Current FIT rate, rate 1 & 2 allows setting a second rate if variable FIT rates (i.e. $0.082 for first 10kWh, then $0.082 thereafter)

    - name: "Electricity - FIT"
      unique_id: electricity_fit
      unit_of_measurement: "€/kWh"
      device_class: monetary
      icon: mdi:cash-plus
      state: >
        {## Enter compensation per kWh rates below ##}
        {% set rate1 = 0.082 %}
        {% set rate2 = 0.082 %}
        {% set fit_exported_today = states('sensor.hs_grid_exported_daily') | float %}
        {% if fit_exported_today <= 10 %} {{rate1}}
        {% else %} {{rate2}}
        {% endif %}


####################################
# IMPORT UTILITY METERS
# See: https://github.com/zeronounours/HA-custom-component-energy-meter

energy_meter:

  hs_grid_imported_daily:
    unique_id: hs_grid_imported_daily
    name: HS Grid - Imported Daily
    source: sensor.power_meter_consumption
    source_type: from_grid
    cycle: daily
    price_entity: &electricity-price sensor.electricity_price

  hs_grid_imported_monthly:
    unique_id: hs_grid_imported_monthly
    name: HS Grid - Imported Monthly
    source: sensor.power_meter_consumption
    source_type: from_grid
    cycle: monthly
    price_entity: *electricity-price

  hs_grid_imported_yearly:
    unique_id: hs_grid_imported_yearly
    name: HS Grid - Imported Yearly
    source: sensor.power_meter_consumption
    source_type: from_grid
    cycle: yearly
    price_entity: *electricity-price


#########################
# EXPORT UTILITY METERS
# See: https://github.com/zeronounours/HA-custom-component-energy-meter

  hs_grid_exported_daily:
    unique_id: hs_grid_exported_daily
    name: HS Grid - Exported Daily
    source: sensor.power_meter_exported
    source_type: to_grid
    cycle: daily
    price_entity: &electricity_fit sensor.electricity_fit

  hs_grid_exported_monthly:
    unique_id: hs_grid_exported_monthly
    name: HS Grid - Exported Monthly
    source: sensor.power_meter_exported
    source_type: to_grid
    cycle: monthly
    price_entity: *electricity_fit

  hs_grid_exported_yearly:
    unique_id: hs_grid_exported_yearly
    name: HS Grid - Exported Yearly
    source: sensor.power_meter_exported
    source_type: to_grid
    cycle: yearly
    price_entity: *electricity_fit

#######################

```
