### DISCUSSION TITLE
setting battery_maximum_discharging_power via own modbus script

### DISCUSSION THREAD

**Discussion by lakatusch** [wlcrs/huawei_solar#642] [General]
hi there,

i tried to set this value by my own modbus script:

```
sequence:
  - service: modbus.write_register
    data:
      address: 47077
      slave: 1
      hub: modbus_huawei
      value: "999"
```
but i get the following error:

`
Pymodbus: modbus_huawei: Error: device: 1 address: 47077 -> Exception Response(134, 6, IllegalAddress)
`

i know that you have realised it in your integration...

And ... if it's not a secret, could you tell us how you realized writing this register?

regards
Daniel

EDIT:
i know its a realy crazy question... therefore i did a sponsoring ;)
