### DISCUSSION TITLE
Estimate inverters  power efficency, yet another way

### DISCUSSION THREAD

**Discussion by torwag** [wlcrs/huawei_solar#663] [Ideas]
Hi,
I was playing with the power efficiency calculations for the inverters.
In the wiki, there is a function, which use some if-clauses to create three steps to approximate the efficiency.
I thought why not using a function and just did that. Digitized the (small) graph from the inverter datasheet into a csv table for all three lines. Wrote a fit function and used the least square function fit, to estimate the function parameters. I came up with an easy function, which would fit reasonable well, taken that the original curves have some bends and dents here and there.
Thought I share the result:

![solar_inverter_efficency](https://github.com/wlcrs/huawei_solar/assets/2484912/95fb280a-6192-4186-9e79-d93fa7c6b635)

The functions I ended up with are:

$\displaystyle E_{470V} = 62.596 \cdot tan^{-1}(2.490 \cdot x)$
$\displaystyle E_{600V} = 62.988 \cdot tan^{-1}(2.998 \cdot x)$
$\displaystyle E_{850V} = 62.711 \cdot tan^{-1}(2.167 \cdot x)$

Where, $E_i$ indicates the resulting efficiency for a given string voltage of $i$ and $x$ the current power input in percent of the maximum power rating of the inverter.

For testing, I implemented the original and the function method and over a day I get the following results for the same inverter

step function approach: 15,062.439 Wh
arctan-function approach: 15,202.522 Wh

Not too much of a difference, but also not too less. Interestingly, I could see that the arctan function results in lower outputs in the morning and evening, but in slightly better output in the day. That would be what I expected, taken that the efficiency esp. for low values might be closer to the original published curve. 

![power_output](https://github.com/wlcrs/huawei_solar/assets/2484912/ff08fbdb-7cc5-4843-bb21-4e07987f1610)

As for how the new sensor template looks like here, it is

```
- sensor:
    - name: "input_power_with_efficiency_loss_arctan"
      unique_id: "input_power_with_efficiency_loss_arctan"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      state: >-
        {% set inverter_rating = 10000 %} {# adjust this value to the rated power of your inverter #}
        {% set inpower = states('sensor.inverter_input_power')|float(0) %}
        {{ inpower * 62.596 * atan(2.490 * inpower/inverter_rating*100)/100}}
```

Disclaimer: I know that this is pretty much an academic/nerd point. I have no idea which approximation is more correct, this would require detailed measurement with external equipment and most likely, the given curves in the datasheet are not really what each individual inverter will do, so at some point there is no accuracy gain at all. Yes, there are much more capable and accurate functions to fit. In particular, above 80% are not a good fit. However, that is a region, I do not reach often with my set-up in my area anyhow. I was looking for something which can easily be implemented in a jinja template and does not ask too much computational power.
Simply:  It just happens, that I teach this kind of stuff and had somehow an hour of fun to apply it here...
