### DISCUSSION TITLE
2 HA connect to the same dongle with TCP Modbus

### DISCUSSION THREAD

**Discussion by Marc911H** [wlcrs/huawei_solar#667] [Connecting to the inverter]
Hello, 
I have 2 HA running & I would like both to poll the same Huawei installation. (tcp modbus port 502)
I saw a post saying, that it is not possible. why ? where is the limitation.

**Comment by j1gg3** [comment]
Only one connection can be established. Use a modbus proxy to allow multiple connections.

**Reply by Marc911H** [reply]
This is a limitation/protection set on the dongle ?

**Reply by j1gg3** [reply]
No, this works as designed. Just one connection is allowed.

**Reply by Roving-Ronin** [reply]
@Marc911H 
Can I ask what your trying to do ? Assuming you have a second HA that you use for testing / development?
If so you can 'replicate' a copy of all the required Huawei sensors from the production HA (with WLCRS integration installed) to the Dev HA, using REST API.

On the Primary HA you need to go to your username (bottom left), then on the Security tab, create a 'Long-Lived Access Token'.  
On the Dev HA create a file say.. rest_huawei_sensors.yaml in your /packages directory, then paste this below into it.

```
################################################################################################
# Replica power sensor, read from source, from target to show on target Home Assistant instance.
# huawei_solar_replicate: v1.0.0
#
# Link: https://github.com/JacobsenKim/ha_huawei_solar_replicate
# How2: https://github.com/JacobsenKim/ha_huawei_solar_replicate/wiki
#
################################################################################################
#
##########################################################################
## !!!!!! Always make sure to back up everything before you begin !!!!! ##
##########################################################################
#
# Replica sensors =
#
# sensor.inverter_input_power (from the Huawei Solar integration)
# sensor.inverter_input_power_2 (from the Huawei Solar integration)
# sensor.inverter_active_power (from the Huawei Solar integration)
# sensor.power_meter_active_power (from the Huawei Solar integration)
# sensor.power_meter_consumption (from the Huawei Solar integration)
# sensor.battery_charge_discharge_power (from the Huawei Solar integration)
# sensor.battery_state_of_capacity (from the Huawei Solar integration)
# sensor.power_meter_exported (from the Huawei Solar integration)
# sensor.battery_day_charge (from the Huawei Solar integration)
# sensor.battery_day_discharge (from the Huawei Solar integration)
# sensor.inverter_daily_yield  (from the Huawei Solar integration)
#
############################################################################
## Replace to fit your info:  ( ip, Authorization token, scan_interval ) ##
############################################################################
############################################################################
## Replace to fit your info:  ( ip, Authorization token, scan_interval ) ##
############################################################################
############################################################################
## Replace to fit your info:  ( ip, Authorization token, scan_interval ) ##
############################################################################
#
sensor:


# sensor.inverter_input_power
  - platform: rest
    name: "Inverter Input Power"
    unique_id: "inverter_input_power"
    resource: "http://192.168.1.100:8123/api/states/sensor.inverter_input_power"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here"
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.inverter_input_power_2
  - platform: rest
    name: "Inverter Input Power 2"
    unique_id: "inverter_input_power_2"
    resource: "http://192.168.1.100:8123/api/states/sensor.inverter_input_power_2"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.inverter_active_power
  - platform: rest
    name: "Inverter Active Power"
    unique_id: "inverter_active_power"
    resource: "http://192.168.1.100:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.inverter_active_power_2
  - platform: rest
    name: "Inverter Active Power 2"
    unique_id: "inverter_active_power_2"
    resource: "http://192.168.1.100:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 10
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.inverter_pv_1_voltage
  - platform: rest
    name: "Inverter - PV 1 Voltage"
    unique_id: inverter_pv_1_voltage
    resource: "http://192.168.1.100:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 10
    icon: mdi:lightening-bolt-outline
    unit_of_measurement: "V"
    state_class: "measurement"
    device_class: voltage


# sensor.inverter_pv_2_voltage
  - platform: rest
    name: "Inverter - PV 2 Voltage"
    unique_id: inverter_pv_2_voltage
    resource: "http://192.168.1.100:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 10
    icon: mdi:lightening-bolt-outline
    unit_of_measurement: "V"
    state_class: "measurement"
    device_class: voltage


# sensor.inverter_pv_1_voltage_2
  - platform: rest
    name: "Inverter - PV 1 Voltage 2"
    unique_id: inverter_pv_1_voltage_2
    resource: "http://192.168.1.100:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 10
    icon: mdi:lightening-bolt-outline
    unit_of_measurement: "V"
    state_class: "measurement"
    device_class: voltage


# sensor.inverter_pv_2_voltage_2
  - platform: rest
    name: "Inverter - PV 2 Voltage 2"
    unique_id: inverter_pv_2_voltage_2
    resource: "http://192.168.1.100:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 10
    icon: mdi:lightening-bolt-outline
    unit_of_measurement: "V"
    state_class: "measurement"
    device_class: voltage


# sensor.power_meter_active_power
  - platform: rest
    name: "Power Meter Active Power"
    unique_id: "power_meter_active_power"
    resource: "http://192.168.1.100:8123/api/states/sensor.power_meter_active_power"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.power_meter_consumption
  - platform: rest
    name: "Power Meter Consumption"
    unique_id: "power_meter_consumption"
    resource: "http://192.168.1.100:8123/api/states/sensor.power_meter_consumption"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:flash
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

# sensor.battery_charge_discharge_power
  - platform: rest
    name: "Battery Charge Discharge Power"
    unique_id: "battery_charge_discharge_power"
    resource: "http://192.168.1.100:8123/api/states/sensor.battery_charge_discharge_power"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:home-battery-outline
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.battery_state_of_capacity
  - platform: rest
    name: "Battery State Of Capacity"
    unique_id: "battery_state_of_capacity"
    resource: "http://192.168.1.100:8123/api/states/sensor.battery_state_of_capacity"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:home-battery
    unit_of_measurement: "%"
    state_class: "measurement"

# sensor.power_meter_exported
  - platform: rest
    name: "Power Meter Exported"
    unique_id: "power_meter_exported"
    resource: "http://192.168.1.100:8123/api/states/sensor.power_meter_exported"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:flash
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

# sensor.battery_day_charge
  - platform: rest
    name: "Battery Day Charge"
    unique_id: "battery_day_charge"
    resource: "http://192.168.1.100:8123/api/states/sensor.battery_day_charge"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:battery-plus-variant
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

# sensor.battery_day_discharge
  - platform: rest
    name: "Battery Day Discharge"
    unique_id: "battery_day_discharge"
    resource: "http://192.168.1.100:8123/api/states/sensor.battery_day_discharge"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:battery-minus-variant
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

# sensor.inverter_daily_yield
  - platform: rest
    name: "Inverter Daily Yield"
    unique_id: "inverter_daily_yield"
    resource: "http://192.168.1.100:8123/api/states/sensor.inverter_daily_yield"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:solar-power
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

###########################################################
#
# PEES Huawei Automation Sensors
#

# sensor.inverter_1_model
  - platform: rest
    name: "Inverter 1 - Model"
    unique_id: "inverter_1_model"
    resource: "http://192.168.1.100:8123/api/states/sensor.inverter_1_model"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here"
      Content-Type: "application/json"
    value_template: "{{ value_json.state }}"
    scan_interval: 30
    icon: phu:huawei-solar-inverter

# sensor.inverter_2_model
  - platform: rest
    name: "Inverter 2 - Model"
    unique_id: "inverter_2_model"
    resource: "http://192.168.1.100:8123/api/states/sensor.inverter_2_model"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here"
      Content-Type: "application/json"
    value_template: "{{ value_json.state }}"
    scan_interval: 30
    icon: phu:huawei-solar-inverter

# sensor.battery_1_model
  - platform: rest
    name: "Battery 1 - Model"
    unique_id: "battery_1_model"
    resource: "http://192.168.1.100:8123/api/states/sensor.battery_1_model"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here"
      Content-Type: "application/json"
    value_template: "{{ value_json.state }}"
    scan_interval: 30
    icon: phu:solar-battery-15

# sensor.battery_2_model
  - platform: rest
    name: "Battery 2 - Model"
    unique_id: "battery_2_model"
    resource: "http://192.168.1.100:8123/api/states/sensor.battery_2_model"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here"
      Content-Type: "application/json"
    value_template: "{{ value_json.state }}"
    scan_interval: 30
    icon: phu:solar-battery-15

# sensor.batteries_installed
  - platform: rest
    name: "Batteries - Installed"
    unique_id: "batteries_installed"
    resource: "http://192.168.1.100:8123/api/states/sensor.batteries_installed"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here"
      Content-Type: "application/json"
    value_template: "{{ value_json.state }}"
    scan_interval: 30
    icon: phu:solar-battery-15

# sensor.batteries_rated_capacity
  - platform: rest
    name: "Batteries - Rated Capacity"
    unique_id: "batteries_rated_capacity"
    resource: "http://192.168.1.100:8123/api/states/sensor.batteries_rated_capacity"
    method: GET
    headers:
      Authorization: "Bearer paste-long-lived-token-here"
      Content-Type: "application/json"
    value_template: "{{ value_json.state }}"
    scan_interval: 30
    icon: mdi:battery-charging-100
```

Update the 192.168.1.100 to the IP of your Primary HA and replace the 'paste-long-lived-token-here' with your actual token.
Note there are a few extra sensors in that list you may not have, as its my config for a Dev HA where I am testing for SunSynk Power Flow card Huawei/iStore support and adding to PEES, that leverage WLCRS and it uses some extra custom sensors. Just delete what you don't need.
