### DISCUSSION TITLE
Possible to obtain data like Inverter Model etc ?

### DISCUSSION THREAD

**Discussion by Roving-Ronin** [wlcrs/huawei_solar#677] [General]
@wlcrs Hi Thijs,

Could you please assist, not being a programmer I can see that in the Huawei_Lib the bridge is providing the ability to 'pull' information such as:

- Inverter No. 1 its Model (i.e. SUN2000-6KTL-M1)
- Inverter No. 2 its Model (i.e. SUN2000-5KTL-L1)
- Battery, if there None/1/2 etc connected. 
- Battery, what capacity they are (i.e. 15kWh)
- How many panels are attached to Inverter 1 / 2 etc.

I notice that in the WLCRS integration if you can to the 'Device Info' some of this information is populated there, such as the model_name (coming from Register 30,000). A quick look at the diagnostics shows, for example:

    "slave_0": {
      "model_name": "SUN2000-5KTL-L1",
      "pv_string_count": 2,
      "has_optimizers": 0,
      "battery_type": 2,
      "battery_1_type": 2,
      "battery_2_type": 0,
      "power_meter_type": 0,
      "supports_capacity_control": true
    },

    "slave_2": {
      "model_name": "SUN2000-5KTL-L1",
      "pv_string_count": 2,
      "has_optimizers": 0,
      "battery_type": 0,
      "battery_1_type": 0,
      "battery_2_type": 0,
      "power_meter_type": null,
      "supports_capacity_control": false
    },

So it looks like your already pulling this information via modbus, just wondering if there's somewhere your storing this that can be accessed? i.e. Buried away as an attribute, that I can use template sensor to pull the atribute out and publish a a sensor(s).

Or is this something where a new 'user-defined-custom-sensors' would be needed to created in the sensor.py file, to have this information (then somehow only triggering it upon start/reboot, so its not queried every 30sec like the normal sensors).

Many thanks for any assistance / direction you can provide.

**Comment by wlcrs** [comment]
Following the [templating docs](https://www.home-assistant.io/docs/configuration/templating/#devices), you can do the following:

```
{{ device_attr("sensor.input_power", "model") }}
{{ device_attr("sensor.inverter_input_power", "serial_number") }}
```

I don't think that there is a way to expose extra device info, as I am limited to what [HA's `DeviceInfo`](https://github.com/home-assistant/core/blob/2df6f1849fbc90157808f5e9cbfec1d33b4d677d/homeassistant/helpers/device_registry.py#L83) supports. Feel free to tinker around with that and submit a PR if you found a clean way to expose that metadata in the `DeviceInfo`.

**Reply by Roving-Ronin** [reply]
Thanks Thijs,

MANY Thanks .. I thought they'd be hiding somewhere. Apologies to ask again, but could you point me in the direction of where to determine what other sensors contain the other info (i.e. pv strings, number of pv, batteries etc.) ? 

Looking in the sensors.py I can see for instance that input_power doesn't even reference having the model attribute. Trying to filter/find them in Developer --> State shows none... not even the model and serial that are under  input_power.

**Reply by wlcrs** [reply]
I don't think that this information can be accessed via HA methods. As already stated: I also don't think that HA supports that, due to the limitation of what I can put into `DeviceInfo`.

The diagnostics feature allows me to write whatever I want into the resulting file, as it is meant to be read by a human: HA does not understand or interpret it. So it is not particularly relevant to what you are asking, as HA must be able to understand that information and store it in a place that is accessible by the end user.

I am not aware of another channel to expose such static information. Feel free to point me in the right direction if you discover that it is possible.

**Reply by Roving-Ronin** [reply]
OK thanks. This was just trying to see if it was possible to 'pull out' things like the inverter model, for use with the Huawei PEES package. Noticed that it currently requires people to manually select they have 1 or 2 inverter and if they are 1 or 3 phase. Then based upon that then get a pull down of L1 / M1 (and trying to add MB0) inverters, thinking that if this info could be queried from HA+WLCRS it would make it possible to use some conditional logic to automate this process (and remove user errors).

**Reply by Roving-Ronin** [reply]
Hi Thijs,

I mean to ask, looking at the underlying code I notice that the Grid Codes that are listed for Australia are only the 'old' ones that Huawei had in the firmware:

AS4777
AS4777-ACT
AS4777-NSW-AG
AS4777-NSW-ESS
AS4777-QLD
AS4777-SA
AS4777-VIC
AS4777-WP

Just wondering if the Grid Code makes any difference within WLCRS, as in H2 2023 the inverter firmware from iirc around SPC155 added the following new Grid Codes for Australia:

![image](https://github.com/wlcrs/huawei_solar/assets/108674933/b42cdf98-5215-4b7a-9ad7-87ea01cf83f5)

Hope this is of assistance.

**Reply by wlcrs** [reply]
The Grid code does not influence any of the sensors exposed in HA

**Comment by Roving-Ronin** [comment]
FYI Thijs,  

Looks good, managed to get this working so we can detect if there's one or two inverters and drop out the model details of:

Huawei          = SUN2000-##KTL-L#  |    SUN2000-##KTL-M#    |    SUN2000-##KTL-MB#   (so 1 and 3 phase)
iStore (OEM)  = IS-HYB-####-1PH     |    IS-HYB-####-3PH (also all the 1 and 3 phase models)

```
template:
  - sensor:
    - name: "Inverter 1 - Model"
      unique_id: inverter_1_model
      icon: mdi:solar-power
      state: >-
        {{ device_attr("sensor.inverter_input_power", "model") | regex_findall_index('(SUN\d+-\d+KTL-[L|M|MB]\d+)|(IS-HYB-\d-\[1|3]PH)', 0) | first }}
      availability: >-
        {{  (states('sensor.inverter_input_power') not in [ 'unknown', 'unavailable', 'none' ] ) }}


  - sensor:
    - name: "Inverter 2 - Model"
      unique_id: inverter_2_model
      icon: mdi:solar-power
      state: >-
        {{ device_attr("sensor.inverter_input_power_2", "model") | regex_findall_index('(SUN\d+-\d+KTL-[L|M|MB]\d+)|(IS-HYB-\d-\[1|3]PH)', 0) | first }}
      availability: >-
        {{  (states('sensor.inverter_input_power_2') not in [ 'unknown', 'unavailable', 'none' ] ) }}
```

Unfortunately doesn't look like there's anywhere to pull the battery model from, with {{ device_attr("sensor.inverter_input_power", "battery_type") }} and {{ device_attr("sensor.inverter_input_power", "battery_1_type") }}  responding with 'None' even though the diagnostic reports:

    "slave_0": {
      "model_name": "SUN2000-5KTL-L1",
      "pv_string_count": 2,
      "has_optimizers": 0,
      "battery_type": 2,
      "battery_1_type": 2,
      "battery_2_type": 0,
      "power_meter_type": 0,
      "supports_capacity_control": true

Was hopeful it could be pulled, that would allow (iirc the values) 1 = LG battery and 2 = LUNA2000 battery. That (or/with a check of one of the standard LUNA sensors status) could then be used to determine how many batteries... then would just need to work out if its a 5/10/15 or a 7/14/21 battery.
