### DISCUSSION TITLE
Loosing all historical data in energy dashboard after adding LUNA2000 batterie

### DISCUSSION THREAD

**Discussion by Mahai17** [wlcrs/huawei_solar#773] [General]
Hi,
I use this integration for more than one year. It is great.
I started without a batterie last year and used "sensor.inverter_daily_yield" for solar production in the energy dashboard. That worked fine. Now, I added a LUNA2000 batterie and I had to add the new entity (Input Yield = Daily Yield - Battery Day Discharge + Battery Day Charge). That works fine as well, but as a consequence, I loose all my historical solar production data in the energy dashboard. 
Is there any chance to preserve the historical data?

Martin Heiden

**Comment by Roving-Ronin** [comment]
I presume your saying g you added a custom sensor, using yaml?

Can you paste it below? What are you trying to g to achieve with this sensor btw ?

As you've described it, adding a custom sensor like this should have zero impact upon the existing inverter daily yield sensor and its data.

BTW also still a good idea to use the HA utility_meter component to take the lifetime yield sensor as the source and define a daily / weekly / monthly / yearly sensor for yield (as well as other things like grid import / export and house consumption).

**Comment by Mahai17** [comment]
Hi Roving,

before having the LUNA2000 I used sensor.inverter_daily_yield for PV Production in the HA Energy Dashboard.
After installing the LUNA2000 I have to use a new sensor, "sensor. solar_ertrag_heute" for PV Production in the HA Energy Dashboard. 
```
      solar_ertrag_heute:
        unit_of_measurement: 'kWh'
        device_class: energy
        value_template: >
          {{ (states('sensor.inverter_daily_yield') | float) - (states('sensor.battery_day_discharge') | float) + (states('sensor.battery_day_charge') | float ) }}
```
That worked fine. But as a consequence of the change I loose all the historical data in the HA Energy Dashboard.

And yes, thanks, I start using HA utility_meter component.
