### ISSUE TITLE
Daily Solar Yield

### ISSUE THREAD

**Issue by woopstar** [wlcrs/huawei_solar#302]
### Describe your feature request

Would'nt the daily solar yield actually just be as simple as:

Daily Solar Yield = Inverter Daily yield - Battery Day discharge

Something like:
```
- sensor:
  - name: "Daily Solar Yield"
    unique_id: "daily_solar_yield"
    state_class: total_increasing
    unit_of_measurement: kWh
    device_class: energy
    icon: mdi:solar-power
    state: >-
      {{ (states('sensor.inverter_daily_yield') | float - states('sensor.battery_day_discharge') | float) | round(3, default=0) }}
```

### Proper usage

- [X] I confirm that this is not a bug report
- [X] I confirm that this feature request is within the stated scope of the integration
