### ISSUE TITLE
[Feature Request]: Separate Battery and Solar yeild

### ISSUE THREAD

**Issue by fredrike** [wlcrs/huawei_solar#309]
### Describe your feature request

The inverter yield seems to be a combination of battery and solar, it would be great if there were a separate sensor for Solar (Daily yield - Battery daily yield).

In the mean time I'll use the following template:

```yaml
template:
  - sensor:
      - name: "Solar daily yield"
        unit_of_measurement: "kWh"
        device_class: energy
        unique_id: solar_daily_yield
        icon: mdi:solar-power-variant
        state: >
          {% set battery = states('sensor.battery_day_discharge') | float %}
          {% set inverter = states('sensor.inverter_daily_yield') | float %}

          {{ (inverter - battery) }}
 ```

### Proper usage

- [X] I confirm that this is not a bug report
- [X] I confirm that this feature request is within the stated scope of the integration
