### ISSUE TITLE
[Feature Request]: Avoid Negative House Load - Poll/Timing optimization

### ISSUE THREAD

**Issue by heinemannj** [wlcrs/huawei_solar#767]
### Describe your feature request

**Negative House Load** (for my setup NOT possible) - potentially due to Poll/Timing mismatch between `Inverter Active power` and `Power meter Active power`:

**NOT recognized in versions 1.3.x**.

**My proposal**:

- dedicated update interval for all power related sensors (inverter, power-meter, batteries): interval 1-10s
- dedicated update interval for all energy related sensors (inverter, power-meter, batteries): interval 10-30s
- for remaining sensors (inverter, power-meter, batteries): interval 30-60s

```
template:
  - trigger:
      - platform: state
        entity_id: sensor.inverter_input_power
        not_from:
          - "unknown"
          - "unavailable"
          - "none"
        not_to:
          - "unknown"
          - "unavailable"
          - "none"
      - platform: state
        entity_id: sensor.inverter_active_power
        not_from:
          - "unknown"
          - "unavailable"
          - "none"
        not_to:
          - "unknown"
          - "unavailable"
          - "none"
      - platform: state
        entity_id: sensor.power_meter_active_power
        not_from:
          - "unknown"
          - "unavailable"
          - "none"
        not_to:
          - "unknown"
          - "unavailable"
          - "none"
    action:
      - variables:
          inv_input_power: "{{ states('sensor.inverter_input_power')|int(0) }}"
          inv_active_power: "{{ states('sensor.inverter_active_power')|int(0) }}"
          bat_charge_discharge_power: "{{ (inv_input_power - inv_active_power)|int(0) }}"
          bat_charge_power: "{{ max(0, bat_charge_discharge_power) }}"
          bat_discharge_power: "{{ -min(0, bat_charge_discharge_power) }}"
          pm_active_power: "{{ states('sensor.power_meter_active_power')|int(0) }}"
          grid_export_power: "{{ max(0, pm_active_power) }}"
          grid_import_power: "{{ -min(0, pm_active_power) }}"
          house_power: "{{ inv_active_power - pm_active_power }}"
          house_power_with_correction: >-
            {% if house_power > 0 %}
              {{ house_power }}
            {% else %}
              {{ states('sensor.house_consumption_power')|float(0) }}
            {% endif %}
    sensor:
      #
      # Correction for House power (to avoid negative load)
      #
      - name: house_consumption_power
        unique_id: house_consumption_power
        #friendly_name: "Power meter House power"
        state_class: measurement
        device_class: power
        unit_of_measurement: "W"
        icon: mdi:home-lightning-bolt
        state: "{{ house_power_with_correction }}"
      #
      # House power without correction (negative load possible)
      #
      - name: house_consumption_power_without_correction
        unique_id: house_consumption_power_without_correction
        #friendly_name: "Power meter House power without_correction"
        state_class: measurement
        device_class: power
        unit_of_measurement: "W"
        icon: mdi:home-lightning-bolt
        state: "{{ house_power }}"
```

**HA log is clean no Huawei solar log entries**.

**Connection directly to inverter internal WLAN** (NOT to the dongle) via dedicated HA WLAN interface - works 100% as expected!!!

![image](https://github.com/wlcrs/huawei_solar/assets/3251642/e00df715-5c1b-442d-9c23-7e57a6fbe40a)
![image](https://github.com/wlcrs/huawei_solar/assets/3251642/2e0d8870-0bde-4066-b2ce-34cb17ff3c3d)

**Customized update interval** in `const.py`:

```
INVERTER_UPDATE_INTERVAL = timedelta(seconds=1)
POWER_METER_UPDATE_INTERVAL = timedelta(seconds=1)
ENERGY_STORAGE_UPDATE_INTERVAL = timedelta(seconds=1)
UPDATE_TIMEOUT = timedelta(seconds=29)
# configuration can only change when edited through FusionSolar web or app
CONFIGURATION_UPDATE_INTERVAL = timedelta(minutes=15)
CONFIGURATION_UPDATE_TIMEOUT = timedelta(minutes=1)
# optimizer data is only refreshed every 5 minutes by the inverter.
OPTIMIZER_UPDATE_INTERVAL = timedelta(minutes=5)
OPTIMIZER_UPDATE_TIMEOUT = timedelta(minutes=1)
```

**Increasing the timedelta seconds to it's default of 30seconds will increasing this issue!!!** - No workarround

![image](https://github.com/wlcrs/huawei_solar/assets/3251642/17c6b553-f46f-46ef-a47c-fa48f096305f)

**Last version** of `HA` and` Huawei Solar Integration`:

## System Information

version | core-2024.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1474
Downloaded Repositories | 53
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 10.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Filebrowser (2.23.0_14), Samba Backup (5.2.0), Terminal & SSH (9.14.0), Studio Code Server (5.15.0), step-ca-client (1.0.2), EMHASS (0.10.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 34
views | 51
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 11, 2024 at 03:54
-- | --
current_recorder_run | July 11, 2024 at 15:30
estimated_db_size | 20580.62 MiB
database_engine | mysql
database_version | 11.2.3

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
used_requests | 6
rooftop_site_count | 1

</details>

### Proper usage

- [X] I confirm that this is not a bug report or support request
- [X] I confirm that this feature request is within the stated scope of the integration
