### ISSUE TITLE
[Feature Request]: add some extra sensors

### ISSUE THREAD

**Issue by tranzitwww** [wlcrs/huawei_solar#915]
### Describe your feature request

Hi,
First great job for this awesome tool!

Can you please add the following Modbus sensors, that are measuring the current month/year energy yield (which are now available thru FusionSolar app/website)?
They have the registers addresses 32116 and 32118 (both uint32)

Also add a option to stop querying the inverter during the night (ex: inverter_inverter_state = standby) for sensors that will only be available during the day (ex: inverter_input_power, inverter_active_power, inverter_pv_1_current, etc...)

```
#/homeassistant/modbus.yaml (how I had them previously in my Modbus integration)
- type: tcp
  host: "1.2.3.4"  #Huawei dongle
  port: 502           #Default Modbus TCP port (new is TCP 6607)
  name: "sun2000_huawei_inverter"
  delay: 0.1              # Delay between requests (in seconds)
  timeout: 3              # Timeout for responses (in seconds)

  sensors:
    # Current month energy yield
    - name: "Inverter - Current month energy yield"
      unique_id: "inverter_current_month_energy_yield"
      unit_of_measurement: "kWh"
      slave: 1
      address: 32116
      data_type: uint32
      scan_interval: 3600
      scale: 0.01
      precision: 2
      device_class: energy

    # Current year energy yield
    - name: "Inverter - Current year energy yield"
      unique_id: "inverter_current_year_energy_yield"
      unit_of_measurement: "kWh"
      slave: 1
      address: 32118
      data_type: uint32
      scan_interval: 3600
      scale: 0.01
      precision: 2
      device_class: energy
```
It will be nice to have the following ones. Now I create them thru templates.yaml
1) House Power consumption - Right now there is no easy way to know how much power is consumed by the house
2) Inverter Available power - How much power you still have available to consume from PV (which normally goes to the grid)
3) Inverter PV 1 and PV 2 power - By default you have voltage and amps and you need to multiply them to find out how much power is produced by each string. :)

```
#/homeassistant/templates.yaml
- sensor:
    - name: "House Power consumption"
      unique_id: house_power_consumption
      unit_of_measurement: "W"
      device_class: power
      state: >-
        {% set ac_production = states('sensor.inverter_active_power') | float(none) %}
        {% set meter_power = states('sensor.power_meter_active_power') | float(none) %}

        {% if ac_production is not none and meter_power is not none %}
          {% if ac_production == 0 %}
            {{ (meter_power | abs) | round(0) }}
          {% else %}
            {% set inverter_time = states.sensor.inverter_active_power.last_updated %}
            {% set meter_time = states.sensor.power_meter_active_power.last_updated %}

            {% if inverter_time is not none and meter_time is not none %}
              {% if (inverter_time - meter_time).total_seconds() | abs <= 60 %}
                {% set power_consumption = (ac_production - meter_power) | round(0) %}
                {{ power_consumption if power_consumption >= 0 else 0 }}
              {% else %}
                0
              {% endif %}
            {% else %}
              0
            {% endif %}
          {% endif %}
        {% else %}
          0
        {% endif %}
      availability: >-
        {{ states('sensor.inverter_active_power') not in ['unknown', 'unavailable', 'none'] and
           states('sensor.power_meter_active_power') not in ['unknown', 'unavailable', 'none'] }}

    - name: "Inverter Available power"
      unique_id: inverter_available_power
      unit_of_measurement: "W"
      device_class: power
      state: >-
        {% set meter_power = states('sensor.power_meter_active_power') | float(0) %}
        {{ (meter_power if meter_power > 0 else 0) | round(0) }}
      availability: >-
        {{ states('sensor.power_meter_active_power') not in ['unknown', 'unavailable', 'none'] }}

    - name: "Inverter PV 1 power"
      unique_id: inverter_pv_1_power
      unit_of_measurement: "W"
      device_class: power
      state: >-
        {% set voltage = states('sensor.inverter_pv_1_voltage') | float(0) %}
        {% set current = states('sensor.inverter_pv_1_current') | float(0) %}
        {{ (voltage * current) | round(0) }}
      availability: >-
        {{ states('sensor.inverter_pv_1_voltage') not in ['unknown', 'unavailable', 'none'] and 
           states('sensor.inverter_pv_1_current') not in ['unknown', 'unavailable', 'none'] }}

    - name: "Inverter PV 2 power"
      unique_id: inverter_pv_2_power
      unit_of_measurement: "W"
      device_class: power
      state: >-
        {% set voltage = states('sensor.inverter_pv_2_voltage') | float(0) %}
        {% set current = states('sensor.inverter_pv_2_current') | float(0) %}
        {{ (voltage * current) | round(0) }}
      availability: >-
        {{ states('sensor.inverter_pv_2_voltage') not in ['unknown', 'unavailable', 'none'] and 
           states('sensor.inverter_pv_2_current') not in ['unknown', 'unavailable', 'none'] }}

```

There are some weird issues when combining two sensors in one (I've tried to fix that using "last_updated" time values.):
1) Modbus timeouts can cause wrong new values for the template sensor, since not all its source bodbus sensors will have real-time data (ex: a old sensor value for inverter_active_power and a recent power_meter_active_power can result in a negative number for my house_power_consumption sensor! Which is completely false.
2) Double the amount of values (the template is triggered each time a source sensor values is changed) and some of them might not be from real-time data.

Home assistant statistics for house_power_consumption and its source sensors when there are no last_updated used.
```
sensor.inverter_active_power,2107,2025-01-10T10:42:13.324Z
sensor.inverter_active_power,1215,2025-01-10T10:42:43.585Z
sensor.inverter_active_power,2048,2025-01-10T10:43:15.284Z
sensor.inverter_active_power,2290,2025-01-10T10:43:52.457Z
sensor.inverter_active_power,927,2025-01-10T10:44:22.249Z
sensor.inverter_active_power,2290,2025-01-10T10:44:52.251Z

sensor.power_meter_active_power,1770,2025-01-10T10:42:13.435Z
sensor.power_meter_active_power,950,2025-01-10T10:42:43.846Z
sensor.power_meter_active_power,311,2025-01-10T10:43:15.386Z
sensor.power_meter_active_power,1946,2025-01-10T10:43:52.557Z
sensor.power_meter_active_power,1099,2025-01-10T10:44:22.811Z
sensor.power_meter_active_power,1946,2025-01-10T10:44:52.764Z

sensor.house_power_consumption,251,2025-01-10T10:42:13.330Z
sensor.house_power_consumption,337,2025-01-10T10:42:13.438Z
sensor.house_power_consumption,-555,2025-01-10T10:42:43.591Z
sensor.house_power_consumption,265,2025-01-10T10:42:43.848Z
sensor.house_power_consumption,1098,2025-01-10T10:43:15.290Z
sensor.house_power_consumption,1737,2025-01-10T10:43:15.389Z
sensor.house_power_consumption,1979,2025-01-10T10:43:52.463Z
sensor.house_power_consumption,344,2025-01-10T10:43:52.561Z
sensor.house_power_consumption,-1019,2025-01-10T10:44:22.255Z
sensor.house_power_consumption,-172,2025-01-10T10:44:22.815Z
sensor.house_power_consumption,1191,2025-01-10T10:44:52.257Z
sensor.house_power_consumption,344,2025-01-10T10:44:52.767Z

```

### Proper usage

- [x] I confirm that this is not a bug report or support request
- [x] I confirm that this feature request is within the stated scope of the integration
